"""WWN background tables. Extracted from WWN 1 pp.11-17."""

# d20 random background table
# Each background includes: free_skill, quick_skills (pick 2), growth (d6), learning (d8)
BACKGROUNDS = {
    1: {
        "name": "Artisan",
        "free_skill": "Craft-0",
        "quick_skills": ["Connect-0", "Exert-0", "Know-0", "Notice-0", "Trade-0"],
        "growth": {1: "+1 Any Stat", 2: "+2 Physical", 3: "+2 Physical", 4: "+2 Mental", 5: "Exert-0", 6: "Any Skill"},
        "learning": {1: "Connect", 2: "Craft", 3: "Exert", 4: "Know", 5: "Notice", 6: "Trade", 7: "Any Combat", 8: "Any Skill"},
    },
    2: {
        "name": "Barbarian",
        "free_skill": "Survive-0",
        "quick_skills": ["Exert-0", "Notice-0", "Punch-0", "Sneak-0", "Survive-0"],
        "growth": {1: "+1 Any Stat", 2: "+2 Physical", 3: "+2 Physical", 4: "+2 Mental", 5: "Exert-0", 6: "Any Skill"},
        "learning": {1: "Exert", 2: "Notice", 3: "Punch", 4: "Ride", 5: "Sneak", 6: "Stab", 7: "Survive", 8: "Shoot"},
    },
    3: {
        "name": "Carter",
        "free_skill": "Ride-0",
        "quick_skills": ["Connect-0", "Craft-0", "Exert-0", "Notice-0", "Trade-0"],
        "growth": {1: "+1 Any Stat", 2: "+2 Physical", 3: "+2 Physical", 4: "+2 Mental", 5: "Ride-0", 6: "Any Skill"},
        "learning": {1: "Connect", 2: "Craft", 3: "Exert", 4: "Notice", 5: "Ride", 6: "Survive", 7: "Trade", 8: "Any Combat"},
    },
    4: {
        "name": "Courtesan",
        "free_skill": "Perform-0",
        "quick_skills": ["Convince-0", "Notice-0", "Perform-0", "Connect-0", "Sneak-0"],
        "growth": {1: "+1 Any Stat", 2: "+2 Mental", 3: "+2 Mental", 4: "+2 Physical", 5: "Connect-0", 6: "Any Skill"},
        "learning": {1: "Connect", 2: "Convince", 3: "Know", 4: "Notice", 5: "Perform", 6: "Sneak", 7: "Survive", 8: "Any Skill"},
    },
    5: {
        "name": "Criminal",
        "free_skill": "Sneak-0",
        "quick_skills": ["Connect-0", "Convince-0", "Notice-0", "Sneak-0", "Trade-0"],
        "growth": {1: "+1 Any Stat", 2: "+2 Mental", 3: "+2 Physical", 4: "+2 Mental", 5: "Connect-0", 6: "Any Skill"},
        "learning": {1: "Connect", 2: "Convince", 3: "Notice", 4: "Sneak", 5: "Stab", 6: "Trade", 7: "Any Combat", 8: "Any Skill"},
    },
    6: {
        "name": "Hunter",
        "free_skill": "Shoot-0",
        "quick_skills": ["Exert-0", "Notice-0", "Sneak-0", "Survive-0", "Shoot-0"],
        "growth": {1: "+1 Any Stat", 2: "+2 Physical", 3: "+2 Physical", 4: "+2 Mental", 5: "Exert-0", 6: "Any Skill"},
        "learning": {1: "Exert", 2: "Notice", 3: "Ride", 4: "Shoot", 5: "Sneak", 6: "Survive", 7: "Trade", 8: "Any Combat"},
    },
    7: {
        "name": "Laborer",
        "free_skill": "Exert-0",
        "quick_skills": ["Craft-0", "Connect-0", "Exert-0", "Notice-0", "Survive-0"],
        "growth": {1: "+1 Any Stat", 2: "+2 Physical", 3: "+2 Physical", 4: "+2 Physical", 5: "Exert-0", 6: "Any Skill"},
        "learning": {1: "Connect", 2: "Craft", 3: "Exert", 4: "Notice", 5: "Ride", 6: "Survive", 7: "Work", 8: "Any Combat"},
    },
    8: {
        "name": "Merchant",
        "free_skill": "Trade-0",
        "quick_skills": ["Connect-0", "Convince-0", "Know-0", "Notice-0", "Trade-0"],
        "growth": {1: "+1 Any Stat", 2: "+2 Mental", 3: "+2 Mental", 4: "+2 Mental", 5: "Connect-0", 6: "Any Skill"},
        "learning": {1: "Administer", 2: "Connect", 3: "Convince", 4: "Know", 5: "Notice", 6: "Trade", 7: "Any Combat", 8: "Any Skill"},
    },
    9: {
        "name": "Noble",
        "free_skill": "Lead-0",
        "quick_skills": ["Administer-0", "Connect-0", "Convince-0", "Know-0", "Lead-0"],
        "growth": {1: "+1 Any Stat", 2: "+2 Mental", 3: "+2 Mental", 4: "+2 Mental", 5: "Connect-0", 6: "Any Skill"},
        "learning": {1: "Administer", 2: "Connect", 3: "Convince", 4: "Know", 5: "Lead", 6: "Notice", 7: "Ride", 8: "Any Combat"},
    },
    10: {
        "name": "Nomad",
        "free_skill": "Ride-0",
        "quick_skills": ["Exert-0", "Notice-0", "Ride-0", "Survive-0", "Shoot-0"],
        "growth": {1: "+1 Any Stat", 2: "+2 Physical", 3: "+2 Physical", 4: "+2 Mental", 5: "Exert-0", 6: "Any Skill"},
        "learning": {1: "Exert", 2: "Know", 3: "Notice", 4: "Ride", 5: "Shoot", 6: "Survive", 7: "Trade", 8: "Any Combat"},
    },
    11: {
        "name": "Peasant",
        "free_skill": "Exert-0",
        "quick_skills": ["Connect-0", "Craft-0", "Exert-0", "Notice-0", "Survive-0"],
        "growth": {1: "+1 Any Stat", 2: "+2 Physical", 3: "+2 Physical", 4: "+2 Physical", 5: "Exert-0", 6: "Any Skill"},
        "learning": {1: "Connect", 2: "Craft", 3: "Exert", 4: "Notice", 5: "Ride", 6: "Sneak", 7: "Survive", 8: "Any Skill"},
    },
    12: {
        "name": "Performer",
        "free_skill": "Perform-0",
        "quick_skills": ["Connect-0", "Convince-0", "Notice-0", "Perform-0", "Sneak-0"],
        "growth": {1: "+1 Any Stat", 2: "+2 Mental", 3: "+2 Physical", 4: "+2 Mental", 5: "Perform-0", 6: "Any Skill"},
        "learning": {1: "Connect", 2: "Convince", 3: "Exert", 4: "Notice", 5: "Perform", 6: "Sneak", 7: "Any Combat", 8: "Any Skill"},
    },
    13: {
        "name": "Physician",
        "free_skill": "Heal-0",
        "quick_skills": ["Convince-0", "Heal-0", "Know-0", "Notice-0", "Trade-0"],
        "growth": {1: "+1 Any Stat", 2: "+2 Mental", 3: "+2 Mental", 4: "+2 Physical", 5: "Know-0", 6: "Any Skill"},
        "learning": {1: "Administer", 2: "Convince", 3: "Craft", 4: "Heal", 5: "Know", 6: "Notice", 7: "Trade", 8: "Any Skill"},
    },
    14: {
        "name": "Priest",
        "free_skill": "Pray-0",
        "quick_skills": ["Administer-0", "Convince-0", "Know-0", "Lead-0", "Pray-0"],
        "growth": {1: "+1 Any Stat", 2: "+2 Mental", 3: "+2 Mental", 4: "+2 Mental", 5: "Pray-0", 6: "Any Skill"},
        "learning": {1: "Administer", 2: "Connect", 3: "Convince", 4: "Know", 5: "Lead", 6: "Pray", 7: "Any Combat", 8: "Any Skill"},
    },
    15: {
        "name": "Sailor",
        "free_skill": "Sail-0",
        "quick_skills": ["Connect-0", "Exert-0", "Notice-0", "Sail-0", "Survive-0"],
        "growth": {1: "+1 Any Stat", 2: "+2 Physical", 3: "+2 Physical", 4: "+2 Mental", 5: "Sail-0", 6: "Any Skill"},
        "learning": {1: "Connect", 2: "Craft", 3: "Exert", 4: "Notice", 5: "Sail", 6: "Survive", 7: "Trade", 8: "Any Combat"},
    },
    16: {
        "name": "Scholar",
        "free_skill": "Know-0",
        "quick_skills": ["Administer-0", "Connect-0", "Convince-0", "Know-0", "Notice-0"],
        "growth": {1: "+1 Any Stat", 2: "+2 Mental", 3: "+2 Mental", 4: "+2 Mental", 5: "Know-0", 6: "Any Skill"},
        "learning": {1: "Administer", 2: "Connect", 3: "Convince", 4: "Heal", 5: "Know", 6: "Notice", 7: "Perform", 8: "Any Skill"},
    },
    17: {
        "name": "Slave",
        "free_skill": "Exert-0",
        "quick_skills": ["Craft-0", "Exert-0", "Notice-0", "Sneak-0", "Survive-0"],
        "growth": {1: "+1 Any Stat", 2: "+2 Physical", 3: "+2 Physical", 4: "+2 Physical", 5: "Sneak-0", 6: "Any Skill"},
        "learning": {1: "Craft", 2: "Exert", 3: "Notice", 4: "Sneak", 5: "Survive", 6: "Work", 7: "Any Combat", 8: "Any Skill"},
    },
    18: {
        "name": "Soldier",
        "free_skill": "Stab-0",
        "quick_skills": ["Exert-0", "Lead-0", "Notice-0", "Ride-0", "Stab-0"],
        "growth": {1: "+1 Any Stat", 2: "+2 Physical", 3: "+2 Physical", 4: "+2 Physical", 5: "Exert-0", 6: "Any Skill"},
        "learning": {1: "Exert", 2: "Lead", 3: "Notice", 4: "Ride", 5: "Shoot", 6: "Sneak", 7: "Stab", 8: "Survive"},
    },
    19: {
        "name": "Thug",
        "free_skill": "Punch-0",
        "quick_skills": ["Connect-0", "Convince-0", "Exert-0", "Notice-0", "Punch-0"],
        "growth": {1: "+1 Any Stat", 2: "+2 Physical", 3: "+2 Physical", 4: "+2 Mental", 5: "Connect-0", 6: "Any Skill"},
        "learning": {1: "Connect", 2: "Convince", 3: "Exert", 4: "Notice", 5: "Punch", 6: "Sneak", 7: "Stab", 8: "Survive"},
    },
    20: {
        "name": "Wanderer",
        "free_skill": "Survive-0",
        "quick_skills": ["Connect-0", "Notice-0", "Ride-0", "Sneak-0", "Survive-0"],
        "growth": {1: "+1 Any Stat", 2: "+2 Physical", 3: "+2 Physical", 4: "+2 Mental", 5: "Survive-0", 6: "Any Skill"},
        "learning": {1: "Connect", 2: "Know", 3: "Notice", 4: "Ride", 5: "Sneak", 6: "Stab", 7: "Survive", 8: "Any Combat"},
    },
}
