"""WWN magic items — tiered magical equipment for treasure generation.

Each item has: name, type, tier (1-5), description, keywords.
Types: weapon, armor, implement, consumable, wondrous.
Tier corresponds to treasure tier and approximate character level range.
"""

MAGIC_ITEMS = [
    # ── Tier 1: Minor (levels 1-2) ────────────────────────────────────────────
    {"name": "Glowstone Pendant", "type": "wondrous", "tier": 1,
     "description": "A smooth river stone that emits soft light on command, illuminating a 20-foot radius. Never needs fuel.",
     "keywords": ["light", "utility"]},
    {"name": "Healer's Salve", "type": "consumable", "tier": 1,
     "description": "A clay pot of luminous paste. Applied to wounds, it heals 1d6+1 HP. Single use.",
     "keywords": ["healing", "consumable"]},
    {"name": "Blade of Sparking", "type": "weapon", "tier": 1,
     "description": "A short sword that crackles with static. +1 to hit. On a critical hit, the target is stunned for 1 round.",
     "keywords": ["bonus_hit", "stun"]},
    {"name": "Ironwood Shield", "type": "armor", "tier": 1,
     "description": "A shield grown from a single ironwood bough. +1 AC. Weighs half as much as a normal shield.",
     "keywords": ["bonus_ac", "light"]},
    {"name": "Wayfinder's Compass", "type": "wondrous", "tier": 1,
     "description": "An ancient brass compass that always points toward the nearest settlement. Functions underground.",
     "keywords": ["navigation", "utility"]},
    {"name": "Cloak of Whispers", "type": "wondrous", "tier": 1,
     "description": "A grey cloak that muffles the wearer's footsteps. +1 to Sneak checks.",
     "keywords": ["stealth", "bonus_skill"]},
    {"name": "Potion of Night Eyes", "type": "consumable", "tier": 1,
     "description": "A dark blue liquid. Grants darkvision (60 feet) for one scene. Single use.",
     "keywords": ["darkvision", "consumable"]},
    {"name": "Messenger Stone", "type": "wondrous", "tier": 1,
     "description": "One of a matched pair of stones. Speaking into one transmits the message to the other within 1 mile.",
     "keywords": ["communication", "utility"]},

    # ── Tier 2: Lesser (levels 3-4) ──────────────────────────────────────────
    {"name": "Frostbite Axe", "type": "weapon", "tier": 2,
     "description": "A hand axe rimed with perpetual frost. +1 to hit, +1d4 cold damage. Water freezes on contact with the blade.",
     "keywords": ["bonus_hit", "cold_damage"]},
    {"name": "Ring of Warding", "type": "wondrous", "tier": 2,
     "description": "A silver ring inscribed with protective glyphs. +1 to all saving throws while worn.",
     "keywords": ["bonus_save", "protection"]},
    {"name": "Armor of the Sentinel", "type": "armor", "tier": 2,
     "description": "Chain mail that warns its wearer of danger. Cannot be surprised while wearing it. AC as chain.",
     "keywords": ["awareness", "chain"]},
    {"name": "Staff of Mending", "type": "implement", "tier": 2,
     "description": "A smooth white staff. Once per day, the wielder can heal a touched creature for 2d6 HP.",
     "keywords": ["healing", "daily_power"]},
    {"name": "Elixir of Fortitude", "type": "consumable", "tier": 2,
     "description": "A thick amber liquid. Grants +2 to Physical saves for one scene. Single use.",
     "keywords": ["bonus_save", "consumable"]},
    {"name": "Boots of Striding", "type": "wondrous", "tier": 2,
     "description": "Leather boots that never wear out. Movement rate increased by 10 feet. Ignore difficult terrain.",
     "keywords": ["movement", "terrain"]},
    {"name": "Quiver of Returning", "type": "wondrous", "tier": 2,
     "description": "Arrows or bolts fired from this quiver reappear inside it at dawn. Holds up to 20 projectiles.",
     "keywords": ["ammunition", "renewable"]},
    {"name": "Amulet of Translation", "type": "wondrous", "tier": 2,
     "description": "A copper amulet set with a tongue-shaped stone. The wearer can understand any spoken language.",
     "keywords": ["language", "utility"]},

    # ── Tier 3: Moderate (levels 5-6) ────────────────────────────────────────
    {"name": "Sunblade", "type": "weapon", "tier": 3,
     "description": "A longsword that blazes with golden light. +2 to hit, +1d6 fire damage. Sheds bright light in 30 feet.",
     "keywords": ["bonus_hit", "fire_damage", "light"]},
    {"name": "Mantle of the Storm", "type": "armor", "tier": 3,
     "description": "A cloak that crackles with lightning. +2 AC. Once per scene, reflect a ranged attack back at the attacker.",
     "keywords": ["bonus_ac", "reflection", "lightning"]},
    {"name": "Scroll of Astral Reaching", "type": "consumable", "tier": 3,
     "description": "A scroll containing the spell Astral Reaching. Any literate character can read it once to teleport up to 3 creatures to a known location.",
     "keywords": ["teleportation", "consumable"]},
    {"name": "Rod of Thunderbolts", "type": "implement", "tier": 3,
     "description": "An iron rod capped with brass. Once per day, fire a 60-foot line of lightning dealing 4d6 damage. Physical save for half.",
     "keywords": ["lightning_damage", "daily_power"]},
    {"name": "Ring of Spell Storing", "type": "wondrous", "tier": 3,
     "description": "Can store one spell of level 3 or lower. The spell can be cast later by anyone wearing the ring.",
     "keywords": ["spell_storage", "versatile"]},
    {"name": "Gauntlets of Might", "type": "wondrous", "tier": 3,
     "description": "Iron gauntlets that grant supernatural strength. +2 to Punch/Stab damage rolls and Exert checks.",
     "keywords": ["bonus_damage", "strength"]},
    {"name": "Cape of the Mountebank", "type": "wondrous", "tier": 3,
     "description": "A dramatic scarlet cape. Once per day, teleport up to 60 feet to a visible location as an Instant action.",
     "keywords": ["teleportation", "daily_power"]},

    # ── Tier 4: Major (levels 7-8) ───────────────────────────────────────────
    {"name": "Doomhammer", "type": "weapon", "tier": 4,
     "description": "A massive warhammer of black iron. +3 to hit, 1d10+3 damage, Shock 6/—. On a natural 20, the target must Physical save or be knocked prone and stunned.",
     "keywords": ["bonus_hit", "stun", "critical"]},
    {"name": "Dragonscale Plate", "type": "armor", "tier": 4,
     "description": "Plate armor forged from true dragon scales. AC 20. Resistance to fire and cold damage (half damage).",
     "keywords": ["high_ac", "fire_resistance", "cold_resistance"]},
    {"name": "Staff of the Archmage", "type": "implement", "tier": 4,
     "description": "A staff of ancient eldwood. +1 to spell attack rolls. Recover 1 Effort at the start of each scene.",
     "keywords": ["spell_bonus", "effort_recovery"]},
    {"name": "Potion of Invulnerability", "type": "consumable", "tier": 4,
     "description": "A shimmering gold liquid. For one scene, reduce all damage taken by 3 (minimum 1). Single use.",
     "keywords": ["damage_reduction", "consumable"]},
    {"name": "Crown of Command", "type": "wondrous", "tier": 4,
     "description": "A circlet of pale gold. Once per day, compel a target within 60 feet to obey a single command (Mental save negates).",
     "keywords": ["compulsion", "daily_power"]},
    {"name": "Cloak of Shadows", "type": "wondrous", "tier": 4,
     "description": "A cloak woven from shadow-stuff. The wearer can become invisible at will (as Perfect Transparency). Attacking ends the effect.",
     "keywords": ["invisibility", "stealth"]},

    # ── Tier 5: Legendary (levels 9-10) ──────────────────────────────────────
    {"name": "Worldbreaker", "type": "weapon", "tier": 5,
     "description": "A greatsword forged in the fires of a dying age. +4 to hit, 2d6+4 damage, Shock 8/—. Ignores magical protections and immunities.",
     "keywords": ["bonus_hit", "ignore_immunity", "legendary"]},
    {"name": "Aegis of the Last Emperor", "type": "armor", "tier": 5,
     "description": "A tower shield of imperishable adamant. +3 AC. Once per day, create a 20-foot dome of force that blocks all attacks for 1 round.",
     "keywords": ["bonus_ac", "force_shield", "daily_power"]},
    {"name": "Orb of Absolute Dominion", "type": "implement", "tier": 5,
     "description": "A sphere of flawless crystal. Once per day, cast any spell of level 3 or lower without expending Effort or a spell slot.",
     "keywords": ["free_casting", "daily_power", "legendary"]},
    {"name": "Philosopher's Stone", "type": "consumable", "tier": 5,
     "description": "A rough red stone that pulses with warmth. Consuming it permanently raises one attribute by 2 (max 18) and heals all HP.",
     "keywords": ["attribute_boost", "permanent", "legendary"]},
    {"name": "Mantle of the Undying", "type": "wondrous", "tier": 5,
     "description": "A cloak that defies death itself. Once per day, when reduced to 0 HP, immediately return to half max HP instead.",
     "keywords": ["death_defiance", "daily_power", "legendary"]},
    {"name": "Ring of Three Wishes", "type": "wondrous", "tier": 5,
     "description": "An ancient ring with three gemstones. Each gem grants one wish-level effect (GM adjudicated). Gems crack after use.",
     "keywords": ["wish", "legendary", "limited_use"]},
]
