"""WWN5 optional classes and WWN4 Gyre class definitions.

WWN5 (pp.167-175): Accursed, Bard, Mageslayer, Wise
WWN4 (pp.344-355): Adunic Invoker, Darian Skinshifter, Kistian Duelist,
                     Llaigisan Beastmaster, Sarulite Blood Priest, Vothite Thought Noble
"""

# Base type mapping: determines which standard partial class a new class replaces
# for HD/AB combo table fallback purposes.
BASE_TYPE_MAP = {
    # Standard
    "expert": "expert",
    "warrior": "warrior",
    "mage": "mage",
    # WWN5
    "accursed": "mage",
    "bard": "expert",
    "mageslayer": "warrior",
    "wise": "expert",
    # Gyre
    "invoker": "mage",
    "skinshifter": "mage",
    "duelist": "mage",
    "beastmaster": "mage",
    "blood_priest": "mage",
    "thought_noble": "mage",
}

# Combos that are explicitly forbidden
INVALID_COMBOS = {
    "mageslayer": {"mage", "accursed", "invoker", "skinshifter", "duelist",
                   "beastmaster", "blood_priest", "thought_noble"},
}

PARTIAL_CLASSES = {
    # ══════════════════════════════════════════════════════════════════════
    # WWN5 OPTIONAL CLASSES
    # ══════════════════════════════════════════════════════════════════════

    "accursed": {
        "description": "Eldritch pact-wielder with otherworldly blade and bolt powers.",
        "base_type": "mage",
        "bonus_skill": "magic",
        "effort_formula": "magic_skill + max(int_mod, cha_mod)",
        "has_spells": False,
        "restrictions": [],
        "art_progression": {1: 2, 2: 1, 3: 0, 4: 1, 5: 1, 6: 1, 7: 0, 8: 1, 9: 0, 10: 1},
        "arts": [
            {"name": "Accursed Blade", "description": "Manifest occult melee weapon: 1d8 or 2H 2d6. Add Magic to damage, Shock 2/15. Use Magic as attack skill."},
            {"name": "Accursed Bolt", "description": "As Accursed Blade but ranged: 1d8+Magic, range 200', -4 in melee. Both hands free."},
            {"name": "Bewitching Distraction", "description": "Commit Effort/day. Main Action: target makes Mental save or becomes dazed, forgetting scene."},
            {"name": "Compelling Shriek", "description": "Once/scene, Commit Effort/day. Main Action: shout command (7 words), targets Mental save or obey for 1 round."},
            {"name": "Devil's Bargain", "description": "Main Action: consecrate a deal. Violators take 1d6/level damage. They know it's magical."},
            {"name": "Dire Pact", "description": "Foes suffer penalty equal to Magic skill on saves vs Accursed arts. You gain 1 System Strain if they succeed."},
            {"name": "Lying Face", "description": "Commit Effort. Disguise as any humanoid of same size."},
            {"name": "Night-Black Eyes", "description": "See in perfect darkness. Main Action: detect enchantment on visible target."},
            {"name": "Pacted Protection", "description": "Choose energy type: immune to natural degrees, half damage from magical attacks."},
            {"name": "Rob Vitality", "description": "Once/scene, On Turn: Commit Effort/scene, target visible foe. Physical save or lose Main Action; you gain it."},
            {"name": "Scourging Curse", "description": "Commit Effort/scene. Main Action: -1 penalty to hit/damage/saves for 1 round/level. Scales at L4 and L9."},
            {"name": "Shadowed Steps", "description": "Move Action: Commit Effort/scene, teleport up to Move distance. No walls or vertical."},
            {"name": "Snaring Speech", "description": "Once/round Instant. Commit Effort/day on failed skill check to persuade. Mental save. +1 System Strain."},
            {"name": "Sorcerous Battery", "description": "Once/day, On Turn: Commit Effort/day. Refresh ally spell slot cast since prior round. +1 System Strain."},
            {"name": "Soul Consumption", "description": "Instant. Commit Effort/day when felling intelligent target with Blade/Bolt. Heal 1d6+level, lose 1 System Strain."},
            {"name": "Tendrils of Night", "description": "On Turn: Commit Effort. Exude tentacles/arms manipulating objects up to 20' away. Your AC, damaged if hurt."},
            {"name": "Unseen Steps", "description": "On Turn: Commit Effort/day. Invisible 1d6+level rounds. Breaks on attack/spell/violent action."},
            {"name": "Weight of Sin", "description": "Main Action: Commit Effort/day. Target Physical save or lose Move for 1d6+level rounds."},
            {"name": "Weeping Wounds", "description": "Once/round Instant. Commit Effort/scene when visible enemy takes damage. Physical save or 1d6/round/level, no healing."},
        ],
    },

    "bard": {
        "description": "Performer charged with the Legacy's power through music, song, and speech.",
        "base_type": "expert",
        "bonus_skill": "perform",
        "effort_formula": "perform_skill + cha_mod",
        "has_spells": False,
        "no_quick_learner": True,
        "no_bonus_focus": True,
        "restrictions": [],
        "art_progression": {1: 2, 2: 1, 3: 0, 4: 1, 5: 0, 6: 1, 7: 0, 8: 1, 9: 0, 10: 1},
        "arts": [
            {"name": "A Thousand Tongues", "description": "Arts understood by all intelligent creatures. Learn new language in a week."},
            {"name": "Battle Cry", "description": "Commit Effort/day, On Turn. Allies gain +1 hit/saves/damage/Shock for 1 round/level. +2 at L4, +3 at L9."},
            {"name": "Cursed Tune", "description": "Commit Effort/scene, Main Action. Target -1 hit/damage/saves for 1 round/level. -2 at L4, -3 at L9."},
            {"name": "Deft Fingers", "description": "Max Readied item count +2."},
            {"name": "Entangle Incantation", "description": "Commit Effort/scene, Instant. Counter foe spellcasting within 60': opposed Int/Magic vs Cha/Perform (+2). Once/round."},
            {"name": "Evoke Emotion", "description": "Commit Effort/day, Main Action. +1 social checks for scene. Can force new Reaction Roll. Not in combat. Once/scene."},
            {"name": "Inspire Dread", "description": "Commit Effort/day, Instant on enemy Morale check. Force two Morale checks. Successes still make Instinct check."},
            {"name": "Keen Senses", "description": "Sight equivalent to 60' even if blinded. Perceive invisible creatures/objects."},
            {"name": "Liberating Song", "description": "Immune to mind/emotion control. Commit Effort/scene Instant: ally in range rerolls Mental save vs such effects."},
            {"name": "Rally", "description": "Commit Effort/day, Main Action. Wounded/fallen ally heals 2d6+level. You gain 1 System Strain."},
            {"name": "Soothe the Savage", "description": "Commit Effort/day, Main Action. Animals/beasts won't attack unless commanded. Breaks if combat starts."},
            {"name": "Soothing Graces", "description": "You and allies lose 1 extra System Strain per night's rest."},
            {"name": "Swift Misdirection", "description": "Commit Effort/scene, Main Action. Tell one sentence to intelligent creature. Mental save or believe for 1 round. Once/scene/creature."},
        ],
    },

    "mageslayer": {
        "description": "Anti-magic combat specialist focused on countering spellcasters.",
        "base_type": "warrior",
        "bonus_skill": "magic",
        "effort_formula": "magic_skill + max(int_mod, con_mod)",
        "has_spells": False,
        "no_bonus_combat_focus": True,
        "no_warrior_hp_bonus": True,
        "restricted_pairings": {"mage", "accursed", "invoker", "skinshifter", "duelist",
                                "beastmaster", "blood_priest", "thought_noble"},
        "restrictions": [],
        "fixed_progression": True,
        "art_progression": {1: 2, 2: 2, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1, 10: 1},
        "fixed_arts_by_level": {
            1: ["Antimage", "Magebane"],
            2: ["Witchfinder", "Spellshield"],
            3: ["Disrupt Sorcery"],
            4: ["Know Your Prey"],
            5: ["Share the Pain"],
            6: ["Dispel Enchantment"],
            7: ["Ward Ally"],
            8: ["Immaculate Body"],
            9: ["Immaculate Mind"],
            10: ["Absolute Negation"],
        },
        "arts": [
            {"name": "Absolute Negation", "description": "Instant, Commit Effort/day. Ignore an unwanted spell or standing magical effect."},
            {"name": "Antimage", "description": "Get one level of Nullifier Focus for free, or free Focus if already have both."},
            {"name": "Dispel Enchantment", "description": "Main Action, Commit Effort/day. Touch acts as Extirpate Arcana. Creatures only, once/target/day."},
            {"name": "Disrupt Sorcery", "description": "On Turn, Commit Effort/scene. Next attack disrupts target casting for rest of round, even on miss."},
            {"name": "Immaculate Body", "description": "Magical transformations/curses last max 1 scene. Cannot kill you, reducing to 1 HP worst case."},
            {"name": "Immaculate Mind", "description": "Impervious to mind-affecting/mind-reading spells. See through illusions and magical invisibility."},
            {"name": "Know Your Prey", "description": "Magic skill treated as 1 higher (max 4). Adds to Effort."},
            {"name": "Magebane", "description": "Add half level (rounded up) to damage on casters from any source. Doesn't stack with Killing Blow."},
            {"name": "Share the Pain", "description": "Instant, Commit Effort/day when targeted by hostile spell. Mental save: caster also affected. Once/round."},
            {"name": "Spellshield", "description": "Spell HP damage automatically halved (rounded down) before saves/resistances."},
            {"name": "Ward Ally", "description": "Instant, Commit Effort/scene. When ally within 30' affected by spell, you take the effect instead. Spell hits you twice if in area."},
            {"name": "Witchfinder", "description": "Main Action, Commit Effort/scene. Gain benefits of Apprehend the Arcane Form spell (no dark-vision)."},
        ],
    },

    "wise": {
        "description": "Low-magic scholar, priest, or oracle for no-magic or low-magic settings.",
        "base_type": "expert",
        "bonus_skill": "pray",  # Default; can be pray/know/magic/survive per GM
        "effort_formula": None,  # Wise do NOT use Effort
        "has_spells": False,
        "no_quick_learner": True,
        "no_bonus_focus": True,
        "restrictions": [],
        "art_categories": ["general", "divination", "curses_and_blessings"],
        "art_progression": {1: 1, 2: 1, 3: 0, 4: 1, 5: 1, 6: 1, 7: 0, 8: 1, 9: 0, 10: 1},
        "arts": [
            # General Arts
            {"name": "Dread Awe", "category": "general", "description": "+1 intimidation checks. Main Action: curse foes -1 Morale. Once/scene."},
            {"name": "Elite Ties", "category": "general", "description": "Audience with figures of importance. Once/session: modest favor from elite."},
            {"name": "Erudite", "category": "general", "description": "Once/day: reroll failed intellectual skill check."},
            {"name": "Folk-Friend", "category": "general", "description": "Commoners help you. Once/day: modest favor from commoner."},
            {"name": "Healer", "category": "general", "description": "+1 Heal checks. Once/day On Turn: auto-succeed stabilizing Mortally Wounded."},
            {"name": "Holy Sanctity", "category": "general", "description": "+1 social checks with friendly locals."},
            {"name": "Personal Impunity", "category": "general", "description": "Harming you is taboo. Only desperate humans initiate violence."},
            {"name": "Skilled", "category": "general", "description": "3 skill points on non-combat skills. Repeatable."},
            # Divination Arts
            {"name": "Compel Truth", "category": "divination", "description": "After ritual, ask question. Cha/Magic check vs Morale+1 or level+6. Success: truthful answer."},
            {"name": "Deliver Oracle", "category": "divination", "description": "Spend day in ritual. Wis/Magic check vs difficulty 8: oracle about future. Quality varies by roll."},
            {"name": "Find Object", "category": "divination", "description": "Ritual to locate animal/object/substance. Wis/Magic vs 8-11. Once/day."},
            {"name": "Read Omens", "category": "divination", "description": "Scene-long ritual (10sp). Wis/Magic vs 10. Impression of success/failure for proposed action. Once/month."},
            # Curses and Blessings
            {"name": "Auspicious Undertaking", "category": "curses_and_blessings", "description": "Main Action: bless plan. Target rerolls 1 failed check or missed hit. Lasts until done or level days."},
            {"name": "Evil Eye", "category": "curses_and_blessings", "description": "Curse/blessing arts now Instant. Still 1/round, look instead of vocalize."},
            {"name": "Ill Fate", "category": "curses_and_blessings", "description": "Main Action: curse target. Next pertinent check at -1. If raw die <= Magic skill, effort goes wrong. Until next relevant check."},
            {"name": "Luck Blessing", "category": "curses_and_blessings", "description": "Main Action: bless target. Next skill check +1. One per creature."},
            {"name": "War Curse", "category": "curses_and_blessings", "description": "Main Action: -2 hit/damage/Shock for scene. Miss on die < Magic skill = hurt self. One at a time."},
        ],
    },

    # ══════════════════════════════════════════════════════════════════════
    # WWN4 GYRE CLASSES
    # ══════════════════════════════════════════════════════════════════════

    "invoker": {
        "description": "Adunic spell-point caster using High Magic spells without Vancian slots.",
        "base_type": "mage",
        "bonus_skill": "magic",
        "effort_formula": None,  # Uses spell points, not Effort
        "has_spells": True,
        "can_be_full": True,
        "spell_point_system": True,
        "restrictions": [],
        "art_progression": {1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0},
        "arts": [],  # No arts by default; Traditional Education focus adds them
        "full_casting": {
            1:  {"max_level": 1, "spell_points": 1, "spells_prepared": 2},
            2:  {"max_level": 1, "spell_points": 3, "spells_prepared": 3},
            3:  {"max_level": 2, "spell_points": 4, "spells_prepared": 4},
            4:  {"max_level": 2, "spell_points": 5, "spells_prepared": 4},
            5:  {"max_level": 3, "spell_points": 6, "spells_prepared": 5},
            6:  {"max_level": 3, "spell_points": 7, "spells_prepared": 6},
            7:  {"max_level": 4, "spell_points": 8, "spells_prepared": 7},
            8:  {"max_level": 4, "spell_points": 9, "spells_prepared": 7},
            9:  {"max_level": 5, "spell_points": 10, "spells_prepared": 8},
            10: {"max_level": 5, "spell_points": 11, "spells_prepared": 9},
        },
        "partial_casting": {
            1:  {"max_level": 1, "spell_points": 1, "spells_prepared": 1},
            2:  {"max_level": 1, "spell_points": 1, "spells_prepared": 3},
            3:  {"max_level": 1, "spell_points": 2, "spells_prepared": 3},
            4:  {"max_level": 1, "spell_points": 2, "spells_prepared": 4},
            5:  {"max_level": 2, "spell_points": 3, "spells_prepared": 4},
            6:  {"max_level": 2, "spell_points": 3, "spells_prepared": 5},
            7:  {"max_level": 2, "spell_points": 4, "spells_prepared": 5},
            8:  {"max_level": 2, "spell_points": 4, "spells_prepared": 6},
            9:  {"max_level": 3, "spell_points": 5, "spells_prepared": 6},
            10: {"max_level": 3, "spell_points": 6, "spells_prepared": 7},
        },
    },

    "skinshifter": {
        "description": "Darian shapeshifter who masters alternate animal and humanoid forms.",
        "base_type": "mage",
        "bonus_skill": "survive",
        "effort_formula": "survive_skill + max(con_mod, cha_mod)",
        "has_spells": False,
        "restrictions": [],
        "form_bonus": {1: 1, 2: 1, 3: 2, 4: 2, 5: 3, 6: 3, 7: 4, 8: 4, 9: 5, 10: 6},
        "art_progression": {1: 2, 2: 1, 3: 0, 4: 1, 5: 1, 6: 1, 7: 0, 8: 1, 9: 1, 10: 0},
        "arts": [
            {"name": "Change Form", "description": "On Turn action: shift to mastered form. One form per level. Max 3 arts per form."},
            {"name": "Eyes of the Hawk", "description": "Telescopic vision, see in dim light. +2 visual Notice checks."},
            {"name": "Feline Leap", "description": "Leap up to 20' horizontal or 10' vertical. No fall damage < 30'."},
            {"name": "Feral Prowess", "description": "+1 to Str, Dex, or Con modifier (max +2) in this form."},
            {"name": "Intrinsic Armor", "description": "Base AC 14 + half level (rounded down) in this form."},
            {"name": "Manifest Wings", "description": "Fly at normal Move +10'."},
            {"name": "Octopus' Embrace", "description": "Extra limbs: 4 Stowed items count as Readied."},
            {"name": "Perfect Mimicry", "description": "Perfectly replicate a specific individual's appearance."},
            {"name": "Pliant Flesh", "description": "On Turn shift between forms. Heal 1d6+level on shift."},
            {"name": "Savage Talons", "description": "1d8 natural weapon (+1 at L3/L6/L9). Shock 2/AC13."},
            {"name": "Sculptor's Beauty", "description": "+1 Cha modifier (max +2) in this form."},
            {"name": "Serpent's Kiss", "description": "Commit Effort/scene: +1d8+Survive damage on natural weapon, or paralysis (Physical save)."},
            {"name": "The Monkey's Road", "description": "Climb at full Move. Cannot be knocked prone."},
            {"name": "Warform", "description": "+2 melee hit. Form bonus applies even in humanoid shape."},
            {"name": "Wisdom of Fin and Scale", "description": "Breathe water. Swim at full Move. Communicate with aquatic creatures."},
        ],
    },

    "duelist": {
        "description": "Kistian martial artist specializing in single-weapon fencing and evasion.",
        "base_type": "mage",
        "bonus_skill": "stab",
        "effort_formula": "stab_skill + max(dex_mod, int_mod)",
        "has_spells": False,
        "warrior_fragility": True,
        "restrictions": ["Cannot benefit from arts while wearing medium/heavy armor or large shield"],
        "favored_weapon_bonus": {1: 1, 2: 1, 3: 2, 4: 2, 5: 3, 6: 3, 7: 4, 8: 4, 9: 5, 10: 5},
        "art_progression": {1: 2, 2: 1, 3: 0, 4: 1, 5: 1, 6: 1, 7: 0, 8: 1, 9: 1, 10: 0},
        "arts": [
            {"name": "Favored Weapon", "description": "Choose one melee weapon type. Use Favored Weapon Bonus as hit bonus."},
            {"name": "Blood for Blood", "description": "When hit, make immediate free melee attack at -4 against attacker."},
            {"name": "Burst of Speed", "description": "Commit Effort/scene: +20' Move for scene."},
            {"name": "Code Duello", "description": "+4 AC and roll hits twice in 1v1 melee (no other combatants in reach)."},
            {"name": "Crushing Superiority", "description": "Attacks can be less lethal + force Instinct check on target."},
            {"name": "Dauntless Step", "description": "Immune to effects that impede movement. Can't be grappled."},
            {"name": "Dodge Doom", "description": "Once/scene: negate one successful attack against you."},
            {"name": "Forced Engagement", "description": "Ignore Screen Ally actions when attacking your chosen target."},
            {"name": "Gentleman's Withdrawal", "description": "Fighting Withdrawal without giving up attack."},
            {"name": "Graceful Leap", "description": "10' leap. Fighting Withdrawal as free action. Immune to < 30' fall damage."},
            {"name": "Lightning Draw", "description": "Always act first in surprise rounds. +4 initiative."},
            {"name": "Piercing Strike", "description": "Target's AC treated as 10 for Shock calculation."},
            {"name": "Spiritual Weapon", "description": "Manifest ghostly copy of favored weapon. Functions as magical weapon."},
            {"name": "Unbindable", "description": "Escape any physical bonds in 1 round. Can't be pinned/grappled."},
            {"name": "Unworthy Rabble", "description": "Reroll failed hits vs 1 HD foes (2 HD at L8)."},
            {"name": "Whirling Evasion", "description": "Base AC = 13 + half level (rounded up) while unarmored."},
        ],
    },

    "beastmaster": {
        "description": "Llaigisan animal companion specialist who bonds with a loyal beast.",
        "base_type": "mage",
        "bonus_skill": "survive",
        "effort_formula": "survive_skill + max(wis_mod, cha_mod)",
        "has_spells": False,
        "restrictions": [],
        "art_progression": {1: 2, 2: 1, 3: 0, 4: 1, 5: 1, 6: 1, 7: 0, 8: 1, 9: 0, 10: 1},
        "arts": [
            {"name": "Bind Companion", "description": "Bond animal companion. Max HD = level+1. One at a time."},
            {"name": "Beast Ward", "description": "Animals won't attack you unless magically compelled."},
            {"name": "Eyes of the Beast", "description": "See/hear through companion's senses at any distance."},
            {"name": "Feral Toughness", "description": "Max HP +companion's natural HD. Base AC 13+half level. Immune to outdoor temperature extremes."},
            {"name": "Howl of Distant Summons", "description": "Summon companion from any distance. Arrives within 1d6 rounds."},
            {"name": "Know the Weak Spot", "description": "Roll damage twice vs beasts/animals, take better."},
            {"name": "Mind Call", "description": "Telepathic link with companion at any distance."},
            {"name": "Natural Weaponry", "description": "1d8 natural weapon attacks. Shock 2/AC13. +1 at L3/L6/L9. Harms non-magically immune."},
            {"name": "Savage Senses", "description": "+2 Notice checks. Track by scent. Cannot be surprised in wilderness."},
            {"name": "Shared Vitality", "description": "Companion HD = your level minimum. Hit bonus >= half HD."},
            {"name": "Swift Healing", "description": "Heal companion 1d6/level. Once/scene."},
            {"name": "Tongue of the Beasts", "description": "Speak with animals as if intelligent. Can negotiate/persuade."},
        ],
    },

    "blood_priest": {
        "description": "Sarulite divine miracle worker who channels faith through vocalized prayer.",
        "base_type": "mage",
        "bonus_skill": "pray",
        "effort_formula": "pray_skill + max(wis_mod, cha_mod)",
        "has_spells": False,
        "restrictions": ["Miracles require vocalization"],
        "art_progression": {1: 2, 2: 1, 3: 0, 4: 1, 5: 1, 6: 1, 7: 0, 8: 1, 9: 0, 10: 1},
        "arts": [
            {"name": "A Thousand Tongues", "description": "Speak/understand any language. +1 reaction rolls."},
            {"name": "Armor of God", "description": "Base AC 15 + half level while active."},
            {"name": "Divine Guidance", "description": "Once/day: ask GM a yes/no question about divine will."},
            {"name": "Fear No Flame", "description": "Immune to one energy type (fire/cold/etc)."},
            {"name": "God Wills It", "description": "Allies in earshot: Morale 12, +1/+2/+3 hit/damage at L1/L5/L10."},
            {"name": "Merciful Healing", "description": "Heal 1d6+2 HP. Scales: 2d6+4 at L4, 4d6+8 at L8."},
            {"name": "Sanctified Ward", "description": "+4 AC/saves, immune to Shock. Enemies Instinct check to target you."},
            {"name": "Smite the Wicked", "description": "+4 hit, level auto damage, roll damage twice on next attack."},
            {"name": "The Light of Faith", "description": "Produce brilliant light. Undead/evil creatures take 1d6/round in it."},
            {"name": "Transubstantiation", "description": "Transmute food/water/simple materials. Create sustenance for 20/level."},
            {"name": "Turn False Life", "description": "Undead of HD <= level flee or are destroyed. Stronger undead save."},
            {"name": "Words of Mercy", "description": "Stabilize all dying allies in earshot as Instant action."},
            {"name": "Wrath of the Most High", "description": "Next hit deals +1d8+level bonus damage."},
        ],
    },

    "thought_noble": {
        "description": "Vothite psychic who manipulates minds with invisible mental arts.",
        "base_type": "mage",
        "bonus_skill": "notice",
        "effort_formula": "notice_skill + max(int_mod, wis_mod)",
        "has_spells": False,
        "restrictions": [
            "All arts invisible to non-magical senses",
            "Successful Mental save = target immune for rest of scene",
        ],
        "art_progression": {1: 2, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1, 10: 1},
        "arts": [
            {"name": "Open Mind", "description": "Detect emotional state of visible creature."},
            {"name": "Block Memory", "description": "Block up to 1 hour of target's memory. Mental save."},
            {"name": "Elicitation of Truth", "description": "Read deep thoughts of helpless/cooperative target (requires Surface Apprehension)."},
            {"name": "Facile Speech", "description": "Upgrade Far Speech: telepathic link at 1 mile/level."},
            {"name": "Far Speech", "description": "Telepathic link 200'/level with willing target."},
            {"name": "Hypercognition", "description": "Eidetic memory. Reroll Int checks."},
            {"name": "Iconograph", "description": "Create perfect mental image. Project illusions within 30'."},
            {"name": "Impress Imperative", "description": "Implant suggestion. Target acts on it when triggered. Mental save."},
            {"name": "Mind Light", "description": "Detect all living minds within 60'. Pinpoint location."},
            {"name": "Mind Over Matter", "description": "Telekinesis: move objects up to 100 lbs within 60'."},
            {"name": "Mirror Mask", "description": "Reroll Mental saves. Detect mind-affecting effects. Feed false info to mind readers."},
            {"name": "Positive Association", "description": "Target regards you favorably. Mental save."},
            {"name": "Read Intent", "description": "Know target's immediate intended action."},
            {"name": "Surface Apprehension", "description": "Read surface thoughts of visible creature. Mental save."},
            {"name": "Thoughts Like Razors", "description": "1d8/level psychic damage. Backlash on save."},
            {"name": "Unthinkable Thought", "description": "Erase concept from target's mind. Mental save. Duration: scene."},
        ],
    },
}
