"""Community environment tags for settlement scene generation.

Each tag provides elements (enemies, friends, complications, things, places)
that scene.py combines to create emergent community exploration scenes. Tags
reflect the Latter Earth setting where communities cling to survival amid
ancient dangers, political intrigue, and the remnants of lost civilizations.
"""

COMMUNITY_TAGS = [
    {
        "name": "Besieged",
        "description": "The community is under threat from an external force and its people are frightened and desperate.",
        "enemies": "The besieging force's scouts, probing the settlement's defenses",
        "friends": "The militia captain organizing the defense, eager for capable allies",
        "complications": "Supplies are running low; rationing has begun and tempers are fraying",
        "things": "A map showing the enemy's camp positions and patrol routes",
        "places": "The hastily reinforced gate, piled with barricades and watched by nervous sentries",
    },
    {
        "name": "Trade Hub",
        "description": "Merchants from distant lands gather here, making the settlement wealthy but cosmopolitan.",
        "enemies": "A thieves' guild that preys on merchants and controls the black market",
        "friends": "A foreign trader with exotic goods and useful information from afar",
        "complications": "A trade dispute between two powerful merchants threatens to erupt into violence",
        "things": "A rare trade good from a distant land, valuable and hard to find elsewhere",
        "places": "The central marketplace, a cacophony of languages and competing vendors",
    },
    {
        "name": "Plague-Touched",
        "description": "A sickness has swept through the community, leaving the survivors fearful and suspicious.",
        "enemies": "Desperate individuals who rob the sick and loot abandoned homes",
        "friends": "A healer working tirelessly despite exhaustion, in need of supplies",
        "complications": "Outsiders are blamed for bringing the plague; violence against strangers is escalating",
        "things": "A herbal remedy that eases symptoms, though the disease has no known cure",
        "places": "The quarantine house where the afflicted are isolated behind locked doors",
    },
    {
        "name": "Holy Site",
        "description": "The community has grown around a place of religious significance, attracting pilgrims and zealots.",
        "enemies": "Heretical fanatics who have twisted the site's original purpose",
        "friends": "A pilgrim with knowledge of distant lands gained through years of travel",
        "complications": "A doctrinal dispute has split the community into hostile factions",
        "things": "A relic associated with the holy site, said to have curative properties",
        "places": "The shrine itself, a structure of ancient stone predating the settlement by centuries",
    },
    {
        "name": "Mining Town",
        "description": "The settlement exists to extract valuable minerals from the earth, its people tough and practical.",
        "enemies": "Claim-jumpers or bandits who prey on ore shipments leaving town",
        "friends": "A veteran miner who knows the deep tunnels and what lurks in them",
        "complications": "A tunnel collapse has trapped miners below; a rescue is underway",
        "things": "An unusual ore sample that might be valuable to the right buyer",
        "places": "The mine entrance, a dark maw framed by timber supports and flickering lanterns",
    },
    {
        "name": "Haunted",
        "description": "The community suffers from supernatural disturbances that defy explanation.",
        "enemies": "An undead presence that terrorizes the settlement at night",
        "friends": "An elder who remembers when the haunting began and suspects the cause",
        "complications": "The hauntings are worsening; some families have already fled",
        "things": "An old journal describing events that preceded the first haunting",
        "places": "The abandoned building at the settlement's edge where the activity is strongest",
    },
    {
        "name": "Frontier Post",
        "description": "A remote outpost at the edge of civilization, where law is thin and danger is constant.",
        "enemies": "Raiders from the wilderness who test the settlement's defenses regularly",
        "friends": "A seasoned ranger who patrols the surrounding territory and knows its dangers",
        "complications": "The garrison is understaffed; another attack could overwhelm the defenders",
        "things": "A detailed survey map of the surrounding wilderness, noting dangers and resources",
        "places": "The watchtower overlooking the approaches, manned day and night",
    },
    {
        "name": "Factional Strife",
        "description": "Two or more powerful groups within the community are locked in a bitter power struggle.",
        "enemies": "Enforcers of the losing faction, desperate and willing to use violence",
        "friends": "A moderate voice caught between factions, seeking outside help to broker peace",
        "complications": "Taking sides is unavoidable; neutrality is seen as betrayal by both parties",
        "things": "Compromising documents that could shift the balance of power between factions",
        "places": "The council hall where heated debates occur, sometimes spilling into the streets",
    },
    {
        "name": "Ruin-Adjacent",
        "description": "The settlement sits near ancient ruins, profiting from and endangered by their proximity.",
        "enemies": "Something that has emerged from the ruins and now threatens the settlement",
        "friends": "A ruin-delver who sells recovered artifacts and knows the safest passages",
        "complications": "The ruins are becoming more active; strange lights and sounds at night",
        "things": "An artifact recovered from the ruins, its purpose unknown but clearly valuable",
        "places": "The edge of the settlement nearest the ruins, where buildings are reinforced and doors face away",
    },
    {
        "name": "River Crossing",
        "description": "The settlement controls a vital bridge or ford, making it a chokepoint for regional travel.",
        "enemies": "River pirates who ambush travelers upstream and downstream of the crossing",
        "friends": "The bridge keeper who knows every traveler's business and shares gossip freely",
        "complications": "Spring floods threaten to wash away the bridge; emergency repairs are needed",
        "things": "A toll chest containing accumulated crossing fees, temptingly unguarded",
        "places": "The bridge itself, a sturdy stone arch with market stalls built along its span",
    },
    {
        "name": "Refugee Camp",
        "description": "Displaced people have gathered here, straining the community's resources and goodwill.",
        "enemies": "Predatory individuals who exploit the refugees' desperation",
        "friends": "A refugee leader organizing their people and negotiating with the locals",
        "complications": "Tensions between refugees and locals are near the breaking point over scarce resources",
        "things": "A valuable heirloom carried by a refugee, their only remaining possession of worth",
        "places": "The tent city that has sprung up outside the settlement walls",
    },
    {
        "name": "Secret Society",
        "description": "A hidden organization operates within the community, pursuing its own agenda.",
        "enemies": "Society enforcers who silence anyone who learns too much about their operations",
        "friends": "A disillusioned member who wants to expose the society's activities",
        "complications": "The society has infiltrated the community's leadership; trust is impossible",
        "things": "A coded ledger detailing the society's members, meetings, and plans",
        "places": "A hidden meeting chamber beneath an ordinary building, accessed through a secret door",
    },
    {
        "name": "Harvest Festival",
        "description": "The community is celebrating a seasonal festival, with feasting, competitions, and lowered guards.",
        "enemies": "Criminals taking advantage of the distraction and reduced security",
        "friends": "A festival organizer who knows everyone in town and is happy to make introductions",
        "complications": "A contest or competition has become deadly serious, with honor and wealth at stake",
        "things": "The festival prize, a valuable item that multiple parties covet",
        "places": "The festival grounds, decorated and crowded, with tents and stages set up",
    },
    {
        "name": "Warlord's Domain",
        "description": "A local strongman rules through intimidation and martial power.",
        "enemies": "The warlord's enforcers who collect tribute and punish dissent",
        "friends": "A resistance organizer working secretly to undermine the warlord's grip",
        "complications": "The warlord is planning a campaign against a neighbor and conscripting locals",
        "things": "The warlord's seal, which can be used to forge orders in their name",
        "places": "The fortified manor where the warlord holds court and stores tribute",
    },
    {
        "name": "Fading Glory",
        "description": "Once a great city, this settlement is a shadow of its former self, crumbling and depopulated.",
        "enemies": "Squatters and criminals who have claimed the abandoned districts",
        "friends": "An elderly resident who remembers the city's greatness and knows its hidden places",
        "complications": "A building collapse has blocked a major thoroughfare, forcing detours through unsafe areas",
        "things": "A fragment of civic art from the city's golden age, still beautiful and valuable",
        "places": "The grand plaza, once bustling, now empty except for weeds and pigeons",
    },
    {
        "name": "Arcane Enclave",
        "description": "Practitioners of magic have established a presence here, drawing curiosity and fear.",
        "enemies": "Anti-magic zealots who want to drive the practitioners out or worse",
        "friends": "A minor practitioner willing to trade small enchantments for favors",
        "complications": "A magical experiment has gone wrong, causing localized disturbances",
        "things": "A scroll containing a minor spell or useful ritual",
        "places": "The practitioners' workshop, warded and guarded, glowing faintly at night",
    },
    {
        "name": "Outlaw Haven",
        "description": "The settlement is known for harboring criminals, deserters, and those fleeing justice.",
        "enemies": "A bounty hunter tracking a target who has taken refuge here",
        "friends": "A reformed criminal who runs a legitimate business but knows the underworld",
        "complications": "A legitimate authority has sent agents to investigate; exposure would be catastrophic",
        "things": "Stolen goods being fenced, including an item recognizable to its rightful owner",
        "places": "The tavern where deals are made and information is traded for coin",
    },
    {
        "name": "Ancient Foundation",
        "description": "The settlement is built directly on top of ancient ruins, its basements opening into older structures.",
        "enemies": "Creatures that emerge from the foundations at night to hunt the streets above",
        "friends": "A builder who has mapped the accessible portions of the undercity",
        "complications": "The ancient foundations are shifting; sinkholes are appearing in the streets",
        "things": "An ancient key found during basement excavation, fitting no modern lock",
        "places": "A cellar where the floor has been broken through, revealing a staircase descending into darkness",
    },
    {
        "name": "Drought-Stricken",
        "description": "Water is scarce and the community is slowly dying of thirst.",
        "enemies": "Water hoarders who control the remaining supply and sell it at extortionate prices",
        "friends": "A dowser who believes they can find a new water source if given protection",
        "complications": "Livestock are dying and crops are failing; famine will follow the drought",
        "things": "An ancient map showing the location of a forgotten well or underground spring",
        "places": "The nearly dry communal well, guarded day and night",
    },
    {
        "name": "Crossroads Inn",
        "description": "The settlement is little more than an inn at a crossroads, but travelers bring news and trouble.",
        "enemies": "Highwaymen who watch the crossroads for vulnerable travelers",
        "friends": "The innkeeper, a shrewd judge of character with an ear for useful rumors",
        "complications": "Two rival groups have arrived simultaneously and the tension is palpable",
        "things": "A message left by a previous traveler, hidden and addressed to whoever finds it",
        "places": "The common room of the inn, smoky and crowded, where all business happens",
    },
    {
        "name": "Fisher Village",
        "description": "A small community that lives by the water, harvesting fish and whatever else the depths provide.",
        "enemies": "Sea creatures driven into shallow waters by something larger hunting deeper down",
        "friends": "An old fisher who has seen strange things in the deep and knows the tides",
        "complications": "The catch has been declining for weeks; something in the water is driving the fish away",
        "things": "A barnacle-encrusted chest hauled up in a fishing net",
        "places": "The docks at dawn, where the boats launch and the day's fortunes are decided",
    },
    {
        "name": "Contested Border",
        "description": "The settlement sits on the border between two rival powers, owing allegiance to neither.",
        "enemies": "Agents of one power trying to force the settlement to declare loyalty",
        "friends": "A neutral diplomat trying to maintain the settlement's independence",
        "complications": "Both sides are applying pressure; choosing one means war with the other",
        "things": "A treaty document that could guarantee the settlement's neutrality if delivered",
        "places": "The boundary marker at the settlement's edge, defaced and re-carved repeatedly",
    },
    {
        "name": "Smuggler's Port",
        "description": "The harbor serves two economies: the legitimate trade above decks and the contraband that moves through hidden channels below.",
        "enemies": "A customs enforcer with a personal grudge against smugglers, willing to use violence",
        "friends": "A smuggler captain who can move people or goods past any blockade for the right price",
        "complications": "A shipment of dangerous contraband has gone missing, and both the smugglers and authorities are searching for it",
        "things": "A manifest listing hidden cargo holds and their contents across a dozen vessels in port",
        "places": "The sea caves beneath the harbor, accessible only at low tide, where goods change hands",
    },
    {
        "name": "Theocracy",
        "description": "The priesthood rules here absolutely, interpreting divine will as civil law and tolerating no dissent.",
        "enemies": "Temple inquisitors who investigate outsiders for heresy and enforce doctrinal compliance",
        "friends": "A quietly skeptical priest who aids travelers while maintaining the appearance of orthodoxy",
        "complications": "A religious observance restricts all commerce and movement; violating it carries severe punishment",
        "things": "A holy text with marginalia questioning the official doctrine, dangerous to possess",
        "places": "The grand temple that serves as courthouse, treasury, and seat of government all at once",
    },
    {
        "name": "Festival of the Dead",
        "description": "The community honors its ancestors with a days-long celebration of remembrance, offerings, and open graves.",
        "enemies": "Actual undead drawn by the rituals, mistaken for celebrants until too late",
        "friends": "A spirit-speaker who can communicate with the honored dead and relay their warnings",
        "complications": "The boundary between living and dead thins during the festival; spirits manifest with increasing frequency",
        "things": "An ancestral mask that allows the wearer to see and speak with the dead until dawn",
        "places": "The necropolis outside town, decorated with lanterns and offerings, thronging with mourners",
    },
    {
        "name": "Artisan Quarter",
        "description": "A district of skilled craftspeople produces goods renowned across the region, fiercely protecting their trade secrets.",
        "enemies": "A rival guild that employs saboteurs to steal techniques and destroy competitors' work",
        "friends": "A master artisan willing to craft a custom item in exchange for rare materials",
        "complications": "A guild dispute has shut down production; both sides seek outside leverage",
        "things": "A sample of the quarter's finest work, demonstrating techniques thought lost to the ages",
        "places": "The guild hall where masters display their masterworks and apprentices compete for positions",
    },
    {
        "name": "Plague Doctor",
        "description": "A mysterious healer has arrived claiming to cure a persistent ailment, but their methods are unorthodox and their motives unclear.",
        "enemies": "The plague doctor's masked assistants, who collect specimens and silence critics",
        "friends": "A local healer suspicious of the newcomer, gathering evidence of harmful practices",
        "complications": "The plague doctor's cure works but has disturbing side effects that manifest weeks later",
        "things": "A vial of the doctor's remedy, which could be analyzed to determine its true nature",
        "places": "The doctor's rented house, curtained and guarded, from which strange smells and sounds emerge at night",
    },
    {
        "name": "Witch Trial",
        "description": "The community is gripped by accusations of sorcery, and a tribunal is deciding the fate of the accused.",
        "enemies": "The chief accuser, who is using the trials to settle personal vendettas",
        "friends": "The accused, who may or may not actually practice magic but is certainly innocent of the specific charges",
        "complications": "The hysteria is spreading; new accusations appear daily, and outsiders are easy targets",
        "things": "Evidence that could exonerate the accused but implicates someone powerful",
        "places": "The tribunal hall where public hearings draw crowds baying for judgment",
    },
    {
        "name": "Slave Market",
        "description": "Bondage is practiced openly here, with human chattel bought and sold in the central square.",
        "enemies": "Slavers who view any interference with their trade as a personal and financial attack",
        "friends": "An abolitionist network operating in secret, helping the enslaved escape",
        "complications": "A person the party knows or has dealt with is on the auction block",
        "things": "A set of master keys to the slave pens, stolen from a careless guard",
        "places": "The auction platform in the market square, surrounded by holding cells",
    },
    {
        "name": "Monster Hunters",
        "description": "The settlement specializes in hunting dangerous creatures, its warriors hardened and its trophy walls impressive.",
        "enemies": "A beast that has turned the tables, now hunting the hunters who pursued it",
        "friends": "A veteran hunter offering to share techniques and local creature knowledge",
        "complications": "The latest hunt went badly; several hunters are missing and the creature is now agitated and aggressive",
        "things": "A trophy from a legendary kill, said to have protective properties",
        "places": "The hunter's lodge where contracts are posted and tales are told over strong drink",
    },
    {
        "name": "Refugee Crisis",
        "description": "A sudden influx of displaced people has overwhelmed the settlement's capacity, creating tension and desperation.",
        "enemies": "Opportunists who exploit the chaos to loot, extort, and settle scores",
        "friends": "An organizer among the refugees trying to maintain order and negotiate with suspicious locals",
        "complications": "Disease is spreading in the overcrowded camps, and the locals are talking about forced expulsion",
        "things": "A sealed diplomatic pouch carried by a refugee, containing messages meant for a distant power",
        "places": "The makeshift camp outside the walls, a maze of tarps and lean-tos",
    },
    {
        "name": "Food Riot",
        "description": "Famine or hoarding has driven the populace to violence over dwindling food supplies.",
        "enemies": "The granary guards who defend the stores with lethal force on the orders of those who control them",
        "friends": "A community leader trying to organize fair distribution before more blood is shed",
        "complications": "The food shortage is artificial; someone is hoarding supplies to drive up prices",
        "things": "A granary key that opens the main food stores, worth killing for in the current climate",
        "places": "The barricaded granary where the remaining food is stored under armed guard",
    },
    {
        "name": "Gladiatorial Arena",
        "description": "Blood sport draws crowds and coin to this settlement, where fighters die for entertainment and profit.",
        "enemies": "The arena master who maintains power through the spectacle and eliminates those who threaten it",
        "friends": "A gladiator seeking freedom, willing to fight alongside anyone who can break the system",
        "complications": "The party is pressured to participate; refusal marks them as cowards, acceptance risks death",
        "things": "A champion's token that grants free passage and respect throughout the settlement",
        "places": "The fighting pit, sand-floored and blood-stained, surrounded by roaring tiers of spectators",
    },
    {
        "name": "Sunken Quarter",
        "description": "A portion of the settlement has sunk into the earth over centuries, its lower floors now underground, its streets become tunnels.",
        "enemies": "Things that have crept up from below to inhabit the sunken buildings",
        "friends": "A resident of the quarter's edge who knows the safe paths through the half-buried streets",
        "complications": "The sinking continues; buildings shift and settle without warning, and the ground floor is now the ceiling",
        "things": "Valuables abandoned in the sinking buildings, preserved by the lack of air below",
        "places": "A former temple whose spire now barely reaches street level, its nave a subterranean cavern",
    },
    {
        "name": "Toll Gate",
        "description": "The settlement controls a narrow passage and charges steep tolls, enriching its rulers at travelers' expense.",
        "enemies": "The toll collectors, who double as enforcers and are not above robbing those who cannot pay",
        "friends": "A merchant who knows a bypass route but needs protection to use it",
        "complications": "The tolls have recently doubled, and a coalition of traders is planning to force the passage",
        "things": "A toll exemption token given to allies of the settlement's ruler, valid for one year",
        "places": "The fortified gatehouse where all traffic is stopped, inspected, and taxed",
    },
    {
        "name": "Orphan Gang",
        "description": "War or plague has left dozens of children without families, and they have organized into a cunning and desperate collective.",
        "enemies": "A criminal boss who uses the orphans as thieves and spies, punishing disobedience harshly",
        "friends": "The gang's leader, a child of surprising intelligence who protects the younger ones fiercely",
        "complications": "The orphans have stolen something important and are being hunted by people who will not show mercy",
        "things": "A cache of small valuables the orphans have hidden, their entire collective wealth",
        "places": "The orphans' hideout in an abandoned building, booby-trapped with childish but effective snares",
    },
    {
        "name": "Alchemist's Row",
        "description": "A street of competing alchemists fills the air with strange fumes and stranger explosions.",
        "enemies": "An alchemist whose experiments have produced a dangerous substance they are willing to weaponize",
        "friends": "A careful practitioner who sells reliable potions and warns against the charlatans",
        "complications": "A recent explosion has contaminated the neighborhood; strange effects manifest without warning",
        "things": "A mislabeled potion of considerable power, sold cheaply by a merchant who does not know its value",
        "places": "The shared waste dump behind the shops, a toxic morass of failed experiments",
    },
    {
        "name": "Veterans' Hall",
        "description": "Retired soldiers have formed a powerful fraternity that wields considerable political influence.",
        "enemies": "A faction of veterans plotting a coup, believing only military rule can save the settlement",
        "friends": "A war-weary veteran who counsels peace and offers tactical advice from hard experience",
        "complications": "The veterans demand respect and deference; slighting one means offending all",
        "things": "A military commendation that grants authority over active soldiers in times of emergency",
        "places": "The hall itself, decorated with battle trophies and memorial plaques, where only members may enter",
    },
    {
        "name": "Night Market",
        "description": "After dark, an unofficial market appears in the streets, selling goods that cannot be traded by daylight.",
        "enemies": "Market enforcers who ensure silence about the market's existence and its clientele",
        "friends": "A vendor who deals in information as readily as goods, always knowing who needs what",
        "complications": "An undercover agent is preparing to raid the market; being present when it happens means arrest",
        "things": "A rare item available nowhere else, priced fairly but sold without questions or guarantees",
        "places": "The lantern-lit alley where stalls appear and vanish nightly, never in the same configuration twice",
    },
    {
        "name": "Flooded District",
        "description": "A quarter of the settlement is permanently waterlogged, its residents moving by boat through streets turned to canals.",
        "enemies": "Aquatic creatures that have moved into the flooded buildings, making some areas impassable",
        "friends": "A boat-poler who knows every channel and sunken obstacle in the district",
        "complications": "The flooding is worsening; the next district is threatened, and a political fight over resources has begun",
        "things": "Goods salvaged from a submerged warehouse, water-damaged but still partially valuable",
        "places": "A rooftop community where displaced residents have built a second settlement above the waterline",
    },
    {
        "name": "Iron Covenant",
        "description": "The settlement is ruled by an inflexible code of laws carved in iron tablets, enforced without exception or mercy.",
        "enemies": "The code enforcers, who carry out punishments mechanically and without personal malice",
        "friends": "A lawyer-advocate who knows the code's loopholes and can argue cases before the tribunal",
        "complications": "An obscure law has been violated unknowingly; the penalty is severe, and the code allows no appeal",
        "things": "A copy of the iron code, annotated with precedents and interpretations by past scholars",
        "places": "The judgment square where sentences are carried out publicly, the iron tablets displayed for all to read",
    },
    {
        "name": "Grave Tenders",
        "description": "The settlement's primary industry is maintaining an enormous cemetery, serving as the burial ground for an entire region.",
        "enemies": "Grave robbers who desecrate the tombs for valuables, operating in organized teams",
        "friends": "The head grave tender, a solemn figure who knows the cemetery's secrets and hidden tombs",
        "complications": "The dead are restless; something is disturbing them, and the nightly patrols have become dangerous",
        "things": "A burial register listing every interment, including those in unmarked and hidden graves",
        "places": "The oldest section of the cemetery, where the tombs date to before the current settlement existed",
    },
    {
        "name": "Windmill Heights",
        "description": "The settlement sits on a windy plateau crowned with windmills that grind grain and pump water for the region.",
        "enemies": "Saboteurs hired by a rival settlement to destroy the windmills and break the community's monopoly",
        "friends": "The mill-master who maintains the mechanisms and knows their ancient engineering intimately",
        "complications": "A critical windmill has broken down; without repair, the water supply will fail within days",
        "things": "A replacement gear of ancient make, compatible with the windmill mechanisms but found in a ruin",
        "places": "The largest windmill's interior, a marvel of wooden engineering with grinding stones the size of carts",
    },
    {
        "name": "Exile's End",
        "description": "The settlement was founded by exiles and outcasts, giving it a fierce independence and deep distrust of authority.",
        "enemies": "Agents of the power that originally exiled the founders, seeking to bring them back to justice",
        "friends": "The settlement's elected speaker, who welcomes all outcasts but demands loyalty in return",
        "complications": "A newly arrived exile is being pursued by forces that threaten the entire settlement",
        "things": "A pardon document that could end the exile for one person, signed but with the name left blank",
        "places": "The founders' hall where the original exiles' stories are preserved in carvings and oral tradition",
    },
    {
        "name": "Puppet Court",
        "description": "The settlement's nominal ruler is a figurehead controlled by hidden powers who pull every string.",
        "enemies": "The puppet masters' agents, who ensure the facade remains intact by eliminating threats",
        "friends": "The puppet ruler themselves, who is aware of their captivity and desperate for liberation",
        "complications": "Multiple factions are vying to become the new puppet masters; the ruler is caught between them",
        "things": "A letter proving the true power behind the throne, explosive if made public",
        "places": "The throne room where the puppet holds court, grand but subtly wrong in its power dynamics",
    },
    {
        "name": "Ferrytown",
        "description": "Built where a wide river can be crossed, the settlement profits from controlling the only ferry service for leagues.",
        "enemies": "River bandits who raid the ferry and extort the town from the water",
        "friends": "The ferry operator, a strong and practical woman who has seen everything the river brings",
        "complications": "The ferry has been sabotaged; until repairs are made, the only crossing is a dangerous swim",
        "things": "A river chart showing depths, currents, and the locations of underwater hazards and wrecks",
        "places": "The ferry landing where travelers wait, trading news while the flat-bottomed boat makes its slow crossing",
    },
    {
        "name": "Tinker's Fair",
        "description": "Traveling inventors and repairers have gathered for a seasonal fair, displaying clockwork marvels and useful gadgets.",
        "enemies": "A tinker whose inventions are weapons in disguise, selling them to dangerous buyers",
        "friends": "A brilliant but impoverished inventor who has created something remarkable and needs a patron",
        "complications": "A demonstration has gone wrong; a device is malfunctioning dangerously and its creator cannot stop it",
        "things": "A clockwork device of genuinely useful function, available for a reasonable price",
        "places": "The fairground where tents and stalls display whirring, clicking, and occasionally exploding inventions",
    },
    {
        "name": "Watchtower Chain",
        "description": "The settlement anchors a chain of signal towers stretching across the frontier, its purpose military vigilance.",
        "enemies": "Infiltrators seeking to blind the watchtower chain by eliminating key stations",
        "friends": "The signal corps commander, a disciplined officer who values competent outsiders",
        "complications": "A tower has gone dark and the relief party has not returned; something has happened on the frontier",
        "things": "A signal codebook that would allow anyone to send authentic military communications",
        "places": "The primary watchtower, its top offering a panoramic view of the surrounding territory",
    },
    {
        "name": "Bone Oracle",
        "description": "The settlement is famous for its oracle who reads fortunes in cast bones, drawing pilgrims from across the region.",
        "enemies": "Fanatics who believe the oracle's prophecies justify violent action against named individuals",
        "friends": "The oracle themselves, a weary figure burdened by knowledge they never asked for",
        "complications": "The oracle has issued a prophecy concerning the party, and the locals are watching to see it fulfilled",
        "things": "A set of divination bones carved from an ancient creature, said to give true readings",
        "places": "The oracle's chamber, thick with incense smoke, where petitioners wait in a long nervous queue",
    },
    {
        "name": "Quarantine Wall",
        "description": "The settlement has walled off a contaminated district, trapping the infected inside with whatever supplies could be spared.",
        "enemies": "Desperate infected who try to break through the wall, threatening to spread the contagion",
        "friends": "A doctor who crosses the wall daily to treat the quarantined, risking infection each time",
        "complications": "Someone important is trapped inside the quarantine, and powerful people are demanding an exception",
        "things": "A supply of the medicine that slows the infection, insufficient for all who need it",
        "places": "The wall itself, hastily built of stone and timber, patrolled by grim-faced guards",
    },
    {
        "name": "Fungal Grotto",
        "description": "The settlement occupies a cavern system where cultivated fungi provide food, light, and building material.",
        "enemies": "A colony of predatory insects that infests the deeper fungal gardens and grows bolder each season",
        "friends": "A fungus farmer who understands the delicate ecology that keeps the settlement fed and lit",
        "complications": "A blight is spreading through the fungal crops; if it reaches the luminous strains, the settlement goes dark",
        "things": "A sample of a new fungal strain that glows intensely and seems to repel certain underground creatures",
        "places": "The great cavern garden, its ceiling lost in darkness, the floor a carpet of bioluminescent growth",
    },
    {
        "name": "Salt Flats",
        "description": "The community harvests salt from vast crystalline flats, a commodity as valuable as silver in the Latter Earth.",
        "enemies": "A rival salt merchant who will use any means to establish a monopoly on the trade",
        "friends": "A salt harvester who knows the flats intimately, including which areas conceal deadly sinkholes",
        "complications": "A caravan of salt has been seized by bandits; without the revenue, the settlement cannot buy grain",
        "things": "A salt crystal formation of unusual color that hums faintly in the presence of sorcery",
        "places": "The blinding white salt flats stretching to the horizon, dotted with harvesting crews and evaporation pools",
    },
    {
        "name": "Pastoral Commune",
        "description": "A peaceful herding community whose apparent tranquility hides simmering tensions beneath the surface.",
        "enemies": "Cattle rustlers who raid the herds under cover of darkness and vanish into the grasslands",
        "friends": "A shepherd elder whose knowledge of the land and its seasonal rhythms is encyclopedic",
        "complications": "A predator is killing livestock but no tracks can be found; suspicion falls on neighbors",
        "things": "A carved horn that, when blown, can be heard for miles across the open grassland",
        "places": "The vast common pasture where the community's herds graze under an enormous sky",
    },
    {
        "name": "Penal Colony",
        "description": "The settlement was founded as a place of exile for criminals and political undesirables from a distant power.",
        "enemies": "A convict warlord who has organized the worst prisoners into a brutal hierarchy",
        "friends": "A wrongly convicted prisoner with valuable skills and a desperate need for allies",
        "complications": "Supply ships from the homeland have stopped coming; starvation looms without self-sufficiency",
        "things": "Pardon papers stolen from the warden's office, blank and ready to be filled in",
        "places": "The stockade walls, built as much to keep prisoners in as dangers out",
    },
    {
        "name": "Ember Wastes Edge",
        "description": "The settlement clings to the margin of a blasted wasteland, serving as the last stop before desolation.",
        "enemies": "Waste-mutated marauders who emerge from the desolation to raid for supplies they cannot produce",
        "friends": "A wasteland scout who guides expeditions into the blasted lands for salvage and exploration",
        "complications": "The wasteland is expanding; each year the settlement loses more arable land to the advancing blight",
        "things": "A sealed canister of pre-catastrophe origin recovered from the wastes, its contents unknown",
        "places": "The last watchtower, overlooking the abrupt line where fertile land ends and scorched earth begins",
    },
    {
        "name": "Timber Camp",
        "description": "A rough settlement of loggers harvesting a great forest, living hard and spending harder.",
        "enemies": "Something ancient in the deep forest that resents the cutting and has begun retaliating",
        "friends": "A veteran lumberjack who knows which groves are safe and which are best left alone",
        "complications": "A logging crew has vanished in the deep forest; search parties are being organized",
        "things": "A cross-section of a felled tree revealing unnatural patterns grown into the wood over centuries",
        "places": "The log-choked river where felled timber is floated downstream to distant markets",
    },
    {
        "name": "Lyceum Town",
        "description": "A center of learning where scholars gather to study, debate, and preserve knowledge from the ages before.",
        "enemies": "A faction of scholars who guard dangerous knowledge and eliminate those who learn too much",
        "friends": "A young academic eager to share research in exchange for field observations from travelers",
        "complications": "A forbidden text has been stolen from the restricted archives; accusations fly in every direction",
        "things": "A partial translation of a pre-human inscription that hints at the location of a lost archive",
        "places": "The great library, its shelves stretching into dusty darkness, smelling of old vellum and lamp oil",
    },
    {
        "name": "Vineyard Estate",
        "description": "The settlement produces wine from ancient vineyards, its wealth and culture tied to the vintage.",
        "enemies": "A jealous rival vintner who poisons competitor vines and bribes merchants to favor their stock",
        "friends": "A jovial vintner who offers hospitality freely and knows every scandal in the settlement",
        "complications": "This year's vintage has unusual properties; those who drink it experience shared hallucinations",
        "things": "A bottle of legendary vintage said to have been pressed from grapes grown in soil of a fallen empire",
        "places": "The terraced hillside vineyards, their orderly rows stretching across slopes bathed in golden light",
    },
    {
        "name": "Tar Pits",
        "description": "The settlement harvests bitumen from natural tar seeps, a valuable but dangerous resource.",
        "enemies": "Creatures preserved and reanimated by the tar's strange properties, lurching from the pits at night",
        "friends": "A tar worker who has learned to read the bubbling patterns to predict dangerous eruptions",
        "complications": "A new seep has opened beneath a residential area; evacuation is chaotic and incomplete",
        "things": "A perfectly preserved ancient weapon pulled from the tar, untouched by centuries of burial",
        "places": "The bubbling tar fields at the settlement's edge, their surface shimmering with iridescent films",
    },
    {
        "name": "Exiled Court",
        "description": "A deposed noble and their retinue have established a government-in-exile, plotting their restoration.",
        "enemies": "Assassins sent by the usurper to eliminate the exiled noble and end their claim permanently",
        "friends": "A loyal retainer who serves the exiled court and can broker introductions to the noble",
        "complications": "The exiled court's funds are nearly exhausted; desperate measures are being considered",
        "things": "The deposed noble's signet ring, proof of their identity and rightful claim to power",
        "places": "The modest manor repurposed as a court, its faded grandeur a painful reminder of lost glory",
    },
    {
        "name": "Bone Orchard",
        "description": "The settlement is surrounded by calcite formations resembling skeletal trees, eerie but mineral-rich.",
        "enemies": "Territorial creatures that use the bone-white formations as camouflage for ambush hunting",
        "friends": "A mineral collector who harvests the calcite for trade and has mapped the safest paths",
        "complications": "The formations are growing, slowly encroaching on the settlement; some believe they are alive",
        "things": "A calcite formation that has grown around and preserved an artifact from a previous age",
        "places": "The edge of the bone orchard, where white spires rise from the earth like the ribs of a buried titan",
    },
    {
        "name": "Glassblower's Village",
        "description": "The settlement is famous for its glass artisans, producing everything from windows to alchemical apparatus.",
        "enemies": "A foreign agent attempting to steal the settlement's closely guarded glassmaking techniques",
        "friends": "A master glassblower who can craft specialized equipment in exchange for rare sand or minerals",
        "complications": "The primary sand source has been contaminated; glass production is failing and livelihoods threatened",
        "things": "A glass lens of extraordinary clarity that reveals things invisible to the naked eye",
        "places": "The glassworks district, its furnaces glowing orange through the night, the air shimmering with heat",
    },
    {
        "name": "Forge Town",
        "description": "The settlement is renowned for its smiths and metalworkers, producing arms and tools of exceptional quality.",
        "enemies": "Industrial saboteurs hired by rival settlements to destroy the forges and steal trade secrets",
        "friends": "A master smith willing to craft exceptional work for those who bring rare materials",
        "complications": "The coal supply has been disrupted; without fuel the forges go cold and the town dies",
        "things": "A blade of ancient make brought in for repair, its metallurgy beyond modern understanding",
        "places": "The great forge hall, its heat felt a street away, ringing with the sound of hammers day and night",
    },
    {
        "name": "Nomad Gathering",
        "description": "A seasonal meeting point where nomadic groups converge to trade, marry, and settle disputes.",
        "enemies": "A blood-feud clan seeking to settle scores during the gathering's relative lawlessness",
        "friends": "A caravan master with contacts among multiple nomad groups and knowledge of safe routes",
        "complications": "A dispute over grazing rights threatens to dissolve the gathering into open warfare",
        "things": "A totem staff that grants its bearer the right to speak at the gathering's council fire",
        "places": "The great tent circle where clan elders gather to adjudicate disputes under ancient custom",
    },
    {
        "name": "Verdant Overgrowth",
        "description": "Unnatural plant growth has overtaken the settlement, with vegetation reclaiming buildings and streets.",
        "enemies": "Carnivorous plants that have grown large enough to threaten livestock and the unwary",
        "friends": "A herbalist who harvests the unique flora for potent remedies found nowhere else",
        "complications": "The growth is accelerating and roots are destroying foundations; the settlement may become unlivable",
        "things": "A fruit from the overgrowth that grants vivid prophetic dreams when consumed",
        "places": "A building entirely consumed by vines and branches, its interior now a living green cathedral",
    },
    {
        "name": "Sorcerer-King's Seat",
        "description": "A magic-user of terrible power rules this settlement as an absolute monarch, feared and obeyed.",
        "enemies": "The sorcerer-king's homunculus spies that watch for disloyalty among the populace",
        "friends": "A palace servant who has learned to navigate the sorcerer-king's moods and whims",
        "complications": "The sorcerer-king demands a tribute of rare spell components; failure means punishment for all",
        "things": "A warding amulet that shields the wearer from the sorcerer-king's scrying for a brief time",
        "places": "The obsidian tower at the settlement's heart, humming with arcane energy day and night",
    },
    {
        "name": "Collapsed Authority",
        "description": "The legitimate government has fallen and no one has filled the vacuum, leaving anarchy.",
        "enemies": "A gang leader carving out territory through intimidation and brutal violence",
        "friends": "A former constable still trying to keep order with nothing but personal conviction",
        "complications": "Three separate groups all claim legitimate authority; none will yield to the others",
        "things": "The former governor's chain of office, a potent symbol that could rally the populace",
        "places": "The empty government hall, its doors hanging open, furniture overturned and records scattered",
    },
    {
        "name": "Monastery Town",
        "description": "A monastic order dominates the settlement, imposing their discipline and rituals on daily life.",
        "enemies": "A zealous inquisitor rooting out perceived heresy among the townsfolk with ruthless efficiency",
        "friends": "A worldly monk who chafes at the order's strictness and secretly aids outsiders",
        "complications": "The monastery's ancient prohibition against something commonplace creates constant friction with residents",
        "things": "A beautifully illuminated manuscript containing forgotten lore the monks guard jealously",
        "places": "The monastery's scriptorium, where monks copy texts by candlelight in reverent silence",
    },
    {
        "name": "Blighted Land",
        "description": "The soil and water around the settlement are poisoned by some ancient contamination no one can explain.",
        "enemies": "Mutated beasts warped by the blight that hunt at the settlement's edges",
        "friends": "A naturalist studying the blight who believes a cure might be found at its source",
        "complications": "Children born here increasingly show signs of the blight's influence; desperation grows",
        "things": "A sample of purified soil from before the blight, preserved in a sealed clay jar",
        "places": "The dead forest at the settlement's border, where trees stand as grey petrified pillars",
    },
    {
        "name": "Quarry Settlement",
        "description": "The community exists to extract stone from massive quarries, its workers tough and its structures imposing.",
        "enemies": "A labor boss who works crews to death and silences complaints with violence",
        "friends": "A stone mason whose skill has earned respect from workers and overseers alike",
        "complications": "A quarry wall has revealed a sealed chamber of pre-human origin; work has halted in fear",
        "things": "A block of unusually colored stone that seems to absorb light and resist chiseling",
        "places": "The great quarry pit, its terraced walls descending into echoing depths far below",
    },
    {
        "name": "Ancestral Crypts",
        "description": "The settlement guards extensive catacombs where generations of dead are interred with reverence.",
        "enemies": "A necromancer who has infiltrated the crypts and is raising the honored dead as servants",
        "friends": "The crypt warden, a solemn figure who knows every passage and every name inscribed below",
        "complications": "Sealed tombs are being found open from the inside; something is waking the dead",
        "things": "A burial gift from an ancient interment, placed with the dead but never meant for mortal hands",
        "places": "The crypt entrance, a heavy stone doorway carved with the names of the settlement's founding families",
    },
]
