"""Community environment tags for settlement scene generation.

Each tag provides elements (enemies, friends, complications, things, places)
that scene.py combines to create emergent community exploration scenes. Tags
reflect the Latter Earth setting where communities cling to survival amid
ancient dangers, political intrigue, and the remnants of lost civilizations.
"""

COMMUNITY_TAGS = [
    {
        "name": "Besieged",
        "description": "The community is under threat from an external force and its people are frightened and desperate.",
        "enemies": "The besieging force's scouts, probing the settlement's defenses",
        "friends": "The militia captain organizing the defense, eager for capable allies",
        "complications": "Supplies are running low; rationing has begun and tempers are fraying",
        "things": "A map showing the enemy's camp positions and patrol routes",
        "places": "The hastily reinforced gate, piled with barricades and watched by nervous sentries",
    },
    {
        "name": "Trade Hub",
        "description": "Merchants from distant lands gather here, making the settlement wealthy but cosmopolitan.",
        "enemies": "A thieves' guild that preys on merchants and controls the black market",
        "friends": "A foreign trader with exotic goods and useful information from afar",
        "complications": "A trade dispute between two powerful merchants threatens to erupt into violence",
        "things": "A rare trade good from a distant land, valuable and hard to find elsewhere",
        "places": "The central marketplace, a cacophony of languages and competing vendors",
    },
    {
        "name": "Plague-Touched",
        "description": "A sickness has swept through the community, leaving the survivors fearful and suspicious.",
        "enemies": "Desperate individuals who rob the sick and loot abandoned homes",
        "friends": "A healer working tirelessly despite exhaustion, in need of supplies",
        "complications": "Outsiders are blamed for bringing the plague; violence against strangers is escalating",
        "things": "A herbal remedy that eases symptoms, though the disease has no known cure",
        "places": "The quarantine house where the afflicted are isolated behind locked doors",
    },
    {
        "name": "Holy Site",
        "description": "The community has grown around a place of religious significance, attracting pilgrims and zealots.",
        "enemies": "Heretical fanatics who have twisted the site's original purpose",
        "friends": "A pilgrim with knowledge of distant lands gained through years of travel",
        "complications": "A doctrinal dispute has split the community into hostile factions",
        "things": "A relic associated with the holy site, said to have curative properties",
        "places": "The shrine itself, a structure of ancient stone predating the settlement by centuries",
    },
    {
        "name": "Mining Town",
        "description": "The settlement exists to extract valuable minerals from the earth, its people tough and practical.",
        "enemies": "Claim-jumpers or bandits who prey on ore shipments leaving town",
        "friends": "A veteran miner who knows the deep tunnels and what lurks in them",
        "complications": "A tunnel collapse has trapped miners below; a rescue is underway",
        "things": "An unusual ore sample that might be valuable to the right buyer",
        "places": "The mine entrance, a dark maw framed by timber supports and flickering lanterns",
    },
    {
        "name": "Haunted",
        "description": "The community suffers from supernatural disturbances that defy explanation.",
        "enemies": "An undead presence that terrorizes the settlement at night",
        "friends": "An elder who remembers when the haunting began and suspects the cause",
        "complications": "The hauntings are worsening; some families have already fled",
        "things": "An old journal describing events that preceded the first haunting",
        "places": "The abandoned building at the settlement's edge where the activity is strongest",
    },
    {
        "name": "Frontier Post",
        "description": "A remote outpost at the edge of civilization, where law is thin and danger is constant.",
        "enemies": "Raiders from the wilderness who test the settlement's defenses regularly",
        "friends": "A seasoned ranger who patrols the surrounding territory and knows its dangers",
        "complications": "The garrison is understaffed; another attack could overwhelm the defenders",
        "things": "A detailed survey map of the surrounding wilderness, noting dangers and resources",
        "places": "The watchtower overlooking the approaches, manned day and night",
    },
    {
        "name": "Factional Strife",
        "description": "Two or more powerful groups within the community are locked in a bitter power struggle.",
        "enemies": "Enforcers of the losing faction, desperate and willing to use violence",
        "friends": "A moderate voice caught between factions, seeking outside help to broker peace",
        "complications": "Taking sides is unavoidable; neutrality is seen as betrayal by both parties",
        "things": "Compromising documents that could shift the balance of power between factions",
        "places": "The council hall where heated debates occur, sometimes spilling into the streets",
    },
    {
        "name": "Ruin-Adjacent",
        "description": "The settlement sits near ancient ruins, profiting from and endangered by their proximity.",
        "enemies": "Something that has emerged from the ruins and now threatens the settlement",
        "friends": "A ruin-delver who sells recovered artifacts and knows the safest passages",
        "complications": "The ruins are becoming more active; strange lights and sounds at night",
        "things": "An artifact recovered from the ruins, its purpose unknown but clearly valuable",
        "places": "The edge of the settlement nearest the ruins, where buildings are reinforced and doors face away",
    },
    {
        "name": "River Crossing",
        "description": "The settlement controls a vital bridge or ford, making it a chokepoint for regional travel.",
        "enemies": "River pirates who ambush travelers upstream and downstream of the crossing",
        "friends": "The bridge keeper who knows every traveler's business and shares gossip freely",
        "complications": "Spring floods threaten to wash away the bridge; emergency repairs are needed",
        "things": "A toll chest containing accumulated crossing fees, temptingly unguarded",
        "places": "The bridge itself, a sturdy stone arch with market stalls built along its span",
    },
    {
        "name": "Refugee Camp",
        "description": "Displaced people have gathered here, straining the community's resources and goodwill.",
        "enemies": "Predatory individuals who exploit the refugees' desperation",
        "friends": "A refugee leader organizing their people and negotiating with the locals",
        "complications": "Tensions between refugees and locals are near the breaking point over scarce resources",
        "things": "A valuable heirloom carried by a refugee, their only remaining possession of worth",
        "places": "The tent city that has sprung up outside the settlement walls",
    },
    {
        "name": "Secret Society",
        "description": "A hidden organization operates within the community, pursuing its own agenda.",
        "enemies": "Society enforcers who silence anyone who learns too much about their operations",
        "friends": "A disillusioned member who wants to expose the society's activities",
        "complications": "The society has infiltrated the community's leadership; trust is impossible",
        "things": "A coded ledger detailing the society's members, meetings, and plans",
        "places": "A hidden meeting chamber beneath an ordinary building, accessed through a secret door",
    },
    {
        "name": "Harvest Festival",
        "description": "The community is celebrating a seasonal festival, with feasting, competitions, and lowered guards.",
        "enemies": "Criminals taking advantage of the distraction and reduced security",
        "friends": "A festival organizer who knows everyone in town and is happy to make introductions",
        "complications": "A contest or competition has become deadly serious, with honor and wealth at stake",
        "things": "The festival prize, a valuable item that multiple parties covet",
        "places": "The festival grounds, decorated and crowded, with tents and stages set up",
    },
    {
        "name": "Warlord's Domain",
        "description": "A local strongman rules through intimidation and martial power.",
        "enemies": "The warlord's enforcers who collect tribute and punish dissent",
        "friends": "A resistance organizer working secretly to undermine the warlord's grip",
        "complications": "The warlord is planning a campaign against a neighbor and conscripting locals",
        "things": "The warlord's seal, which can be used to forge orders in their name",
        "places": "The fortified manor where the warlord holds court and stores tribute",
    },
    {
        "name": "Fading Glory",
        "description": "Once a great city, this settlement is a shadow of its former self, crumbling and depopulated.",
        "enemies": "Squatters and criminals who have claimed the abandoned districts",
        "friends": "An elderly resident who remembers the city's greatness and knows its hidden places",
        "complications": "A building collapse has blocked a major thoroughfare, forcing detours through unsafe areas",
        "things": "A fragment of civic art from the city's golden age, still beautiful and valuable",
        "places": "The grand plaza, once bustling, now empty except for weeds and pigeons",
    },
    {
        "name": "Arcane Enclave",
        "description": "Practitioners of magic have established a presence here, drawing curiosity and fear.",
        "enemies": "Anti-magic zealots who want to drive the practitioners out or worse",
        "friends": "A minor practitioner willing to trade small enchantments for favors",
        "complications": "A magical experiment has gone wrong, causing localized disturbances",
        "things": "A scroll containing a minor spell or useful ritual",
        "places": "The practitioners' workshop, warded and guarded, glowing faintly at night",
    },
    {
        "name": "Outlaw Haven",
        "description": "The settlement is known for harboring criminals, deserters, and those fleeing justice.",
        "enemies": "A bounty hunter tracking a target who has taken refuge here",
        "friends": "A reformed criminal who runs a legitimate business but knows the underworld",
        "complications": "A legitimate authority has sent agents to investigate; exposure would be catastrophic",
        "things": "Stolen goods being fenced, including an item recognizable to its rightful owner",
        "places": "The tavern where deals are made and information is traded for coin",
    },
    {
        "name": "Ancient Foundation",
        "description": "The settlement is built directly on top of ancient ruins, its basements opening into older structures.",
        "enemies": "Creatures that emerge from the foundations at night to hunt the streets above",
        "friends": "A builder who has mapped the accessible portions of the undercity",
        "complications": "The ancient foundations are shifting; sinkholes are appearing in the streets",
        "things": "An ancient key found during basement excavation, fitting no modern lock",
        "places": "A cellar where the floor has been broken through, revealing a staircase descending into darkness",
    },
    {
        "name": "Drought-Stricken",
        "description": "Water is scarce and the community is slowly dying of thirst.",
        "enemies": "Water hoarders who control the remaining supply and sell it at extortionate prices",
        "friends": "A dowser who believes they can find a new water source if given protection",
        "complications": "Livestock are dying and crops are failing; famine will follow the drought",
        "things": "An ancient map showing the location of a forgotten well or underground spring",
        "places": "The nearly dry communal well, guarded day and night",
    },
    {
        "name": "Crossroads Inn",
        "description": "The settlement is little more than an inn at a crossroads, but travelers bring news and trouble.",
        "enemies": "Highwaymen who watch the crossroads for vulnerable travelers",
        "friends": "The innkeeper, a shrewd judge of character with an ear for useful rumors",
        "complications": "Two rival groups have arrived simultaneously and the tension is palpable",
        "things": "A message left by a previous traveler, hidden and addressed to whoever finds it",
        "places": "The common room of the inn, smoky and crowded, where all business happens",
    },
    {
        "name": "Fisher Village",
        "description": "A small community that lives by the water, harvesting fish and whatever else the depths provide.",
        "enemies": "Sea creatures driven into shallow waters by something larger hunting deeper down",
        "friends": "An old fisher who has seen strange things in the deep and knows the tides",
        "complications": "The catch has been declining for weeks; something in the water is driving the fish away",
        "things": "A barnacle-encrusted chest hauled up in a fishing net",
        "places": "The docks at dawn, where the boats launch and the day's fortunes are decided",
    },
    {
        "name": "Contested Border",
        "description": "The settlement sits on the border between two rival powers, owing allegiance to neither.",
        "enemies": "Agents of one power trying to force the settlement to declare loyalty",
        "friends": "A neutral diplomat trying to maintain the settlement's independence",
        "complications": "Both sides are applying pressure; choosing one means war with the other",
        "things": "A treaty document that could guarantee the settlement's neutrality if delivered",
        "places": "The boundary marker at the settlement's edge, defaced and re-carved repeatedly",
    },
]
