"""Ruin environment tags for dungeon/ruin scene generation.

Each tag provides elements (enemies, friends, complications, things, places)
that scene.py combines to create emergent ruin exploration scenes. Tags draw
from the Latter Earth setting where ancient civilizations left behind vast
networks of ruins, underground complexes, and magical infrastructure.
"""

RUIN_TAGS = [
    {
        "name": "Collapsed Archive",
        "description": "Shelves of stone tablets and scroll cases line the walls, most shattered by the ceiling's partial collapse.",
        "enemies": "Vermin swarms nesting in the debris, aggressive when their lairs are disturbed",
        "friends": "A scholar trapped under rubble, alive but pinned and weakening",
        "complications": "The remaining ceiling is unstable; loud noise or vibration risks further collapse",
        "things": "An intact scroll case containing a readable document in an ancient tongue",
        "places": "A reading alcove miraculously untouched, its stone desk still bearing open tablets",
    },
    {
        "name": "Flooded Crypt",
        "description": "Black water fills this burial chamber to knee depth, disturbed coffins floating among the debris.",
        "enemies": "Waterlogged undead that rise silently from beneath the surface",
        "friends": "A treasure hunter clinging to a ledge above the waterline, too frightened to continue alone",
        "complications": "The water is rising slowly — a blocked drain somewhere is backing up",
        "things": "A sealed reliquary floating among the debris, its contents waterproof",
        "places": "A raised stone platform where the most important sarcophagus rests above the flood",
    },
    {
        "name": "Mechanical Chamber",
        "description": "Gears, pistons, and cables of an incomprehensible machine fill this room, some still clicking.",
        "enemies": "A malfunctioning automaton that attacks anything that moves within its patrol zone",
        "friends": "A tinkerer who has partially decoded the machine's purpose and needs help with a repair",
        "complications": "The machine is still partially active; touching the wrong component could trigger a dangerous cycle",
        "things": "A control lever that seems to govern some function deeper in the ruin",
        "places": "A maintenance crawlspace behind the machine, leading to another section of the complex",
    },
    {
        "name": "Fungal Garden",
        "description": "Luminescent fungi carpet the floor and walls, casting the chamber in eerie blue-green light.",
        "enemies": "Insectoid creatures that cultivate the fungi and attack intruders as threats to their crop",
        "friends": "An alchemist harvesting rare fungal specimens, willing to trade medicinal preparations",
        "complications": "Some fungi release paralytic spores when disturbed; the safe path is narrow",
        "things": "A cluster of rare medicinal fungi worth considerable coin to an apothecary",
        "places": "A deeper grotto where the fungi grow enormous, their caps forming a false ceiling",
    },
    {
        "name": "Obsidian Mirror",
        "description": "A massive polished obsidian surface dominates one wall, its reflection subtly wrong.",
        "enemies": "A creature that lurks behind the mirror, emerging to hunt when prey draws close",
        "friends": "A mystic studying the mirror's properties, believing it shows other places or times",
        "complications": "The mirror seems to show a slightly different version of the room — with something else in it",
        "things": "A silver frame around the mirror set with gemstones in a pattern that might be a key",
        "places": "The space directly before the mirror, where sound behaves strangely",
    },
    {
        "name": "Sacrificial Hall",
        "description": "A tiered amphitheater descends to a blood-stained altar at its center.",
        "enemies": "Cultists who have reconsecrated the altar and use the ruin for their ceremonies",
        "friends": "A prisoner awaiting sacrifice, bound and gagged on the lower tiers",
        "complications": "The altar radiates a palpable wrongness; lingering near it causes nausea and dread",
        "things": "A ceremonial blade of ancient make, still sharp and stained with old blood",
        "places": "A hidden preparation chamber behind the altar, accessible through a pivoting wall section",
    },
    {
        "name": "Crystal Vault",
        "description": "The walls of this chamber are lined with crystalline formations that refract light into rainbow patterns.",
        "enemies": "A crystal-armored creature that is nearly invisible against the glittering walls",
        "friends": "A trapped prospector who knows the crystals' value but cannot carry enough alone",
        "complications": "The crystals amplify sound painfully; combat here is deafening",
        "things": "A crystal lens that focuses light into a cutting beam when held at the right angle",
        "places": "A natural alcove where the crystals have grown into a throne-like formation",
    },
    {
        "name": "Sealed Ward",
        "description": "Heavy doors marked with warning glyphs stand partially open, their seals broken from within.",
        "enemies": "Whatever was imprisoned here, now loose in the surrounding chambers",
        "friends": "A warden-descendant who knows the sealing rituals but lacks the strength to perform them alone",
        "complications": "The ward's magical containment is failing; reality feels thin and wrong near the breach",
        "things": "A warden's key that can reactivate certain containment measures",
        "places": "The innermost cell, its walls covered in scratch marks and desperate inscriptions",
    },
    {
        "name": "Aqueduct Junction",
        "description": "Water channels from multiple directions converge here in a hub of ancient hydraulic engineering.",
        "enemies": "Aquatic predators that use the channels as highways through the ruin",
        "friends": "An engineer studying the water system, mapping the ruin's layout through its plumbing",
        "complications": "One channel is blocked; water pressure is building and may burst through",
        "things": "A valve wheel that controls water flow to different sections of the complex",
        "places": "A dry maintenance corridor running alongside the main channel",
    },
    {
        "name": "Bone Ossuary",
        "description": "The walls are constructed entirely from carefully arranged human bones, stacked floor to ceiling.",
        "enemies": "Undead assembled from the ossuary bones, collapsing and reforming endlessly",
        "friends": "A priest performing rites for the dead, trying to bring peace to the restless spirits",
        "complications": "Disturbing the bones triggers a cascading collapse of the wall sections",
        "things": "A skull marked with gold leaf and gems, clearly someone of great importance",
        "places": "A central chamber where a single intact skeleton sits on a chair, hands folded",
    },
    {
        "name": "Forge Level",
        "description": "Anvils, quenching troughs, and cold furnaces fill this industrial section of the ruin.",
        "enemies": "A fire elemental or golem bound to the forge, still following its last orders",
        "friends": "A smith who has rekindled one furnace and is producing simple tools for a nearby settlement",
        "complications": "Gas pockets in the forge vents; an open flame could trigger an explosion",
        "things": "An unfinished masterwork weapon on the anvil, needing only final tempering",
        "places": "The master smith's private workroom, its door sealed with a puzzle lock",
    },
    {
        "name": "Garden Atrium",
        "description": "A vast skylit chamber where plants have run wild, roots cracking the stone floor.",
        "enemies": "Predatory plants that have evolved in isolation, their vines quick and grasping",
        "friends": "A herbalist who has discovered medicinal species found nowhere else",
        "complications": "The root system has compromised the floor's integrity; sections may give way",
        "things": "Seeds of a plant thought extinct, viable if planted in the right conditions",
        "places": "A stone gazebo at the garden's center, overgrown but structurally sound",
    },
    {
        "name": "Echo Gallery",
        "description": "A long corridor where every sound repeats and amplifies, making stealth impossible.",
        "enemies": "Blind predators that navigate by echolocation, drawn to any noise",
        "friends": "A musician who has learned to use the echoes to map hidden passages",
        "complications": "Combat sounds attract every creature in adjacent chambers",
        "things": "A pair of wax earplugs enchanted to muffle sound while allowing speech",
        "places": "An acoustic dead spot where sound does not carry — a perfect hiding place",
    },
    {
        "name": "Gravity Well",
        "description": "A section where gravity pulls in the wrong direction, sending debris floating upward.",
        "enemies": "Creatures adapted to the inverted gravity that attack from unexpected angles",
        "friends": "An explorer tethered to a pillar, studying the anomaly with makeshift instruments",
        "complications": "The gravity shifts unpredictably; what's down becomes up without warning",
        "things": "A device at the anomaly's center that might be causing the distortion",
        "places": "A ceiling that has become a floor, complete with furniture bolted to it",
    },
    {
        "name": "Painted Hall",
        "description": "Every surface is covered in vivid murals depicting the daily life of the ruin's former inhabitants.",
        "enemies": "Guardians triggered by anyone who damages the murals",
        "friends": "An artist carefully copying the murals before they fade completely",
        "complications": "The murals contain a hidden message visible only by torchlight from a specific angle",
        "things": "Pigments used in the murals, still vivid after millennia — extremely valuable",
        "places": "A concealed door painted to blend seamlessly with the surrounding mural",
    },
    {
        "name": "Prison Block",
        "description": "Rows of iron-barred cells line a central corridor, some still locked, others torn open.",
        "enemies": "The descendants of the original prisoners, gone feral over generations of isolation",
        "friends": "A recent captive locked in a cell by the current inhabitants of the ruin",
        "complications": "The locking mechanism is connected to a trap system; opening one cell triggers another",
        "things": "A prisoner's journal scratched into the wall, describing the ruin's layout",
        "places": "The warden's office at the corridor's end, with keys still hanging on the wall",
    },
    {
        "name": "Throne Room",
        "description": "A grand chamber dominated by a stone throne on a raised dais, its former glory faded but evident.",
        "enemies": "A powerful creature that has claimed the throne room as its lair",
        "friends": "A claimant to the ruined domain seeking allies to help secure the throne",
        "complications": "The throne is trapped — sitting in it activates ancient defensive systems",
        "things": "A crown resting on the throne, tarnished but set with stones of evident value",
        "places": "A hidden passage behind the throne leading to private chambers",
    },
    {
        "name": "Refuse Pit",
        "description": "A deep shaft where the ruin's inhabitants once dumped waste, now a stratified archaeological record.",
        "enemies": "A massive scavenger creature that nests in the accumulated refuse",
        "friends": "A treasure-sifter who has found valuable discards and knows the pit's safe ledges",
        "complications": "The refuse produces methane; bringing fire here risks a devastating explosion",
        "things": "A discarded item of surprising value buried in the muck",
        "places": "A ledge halfway down the pit with access to a sealed side passage",
    },
    {
        "name": "Alchemical Laboratory",
        "description": "Glass vessels, metal retorts, and stone basins crowd this chamber, some still containing liquids.",
        "enemies": "A creature spawned or mutated by the ancient chemicals still active in the lab",
        "friends": "An alchemist who has identified several still-potent reagents",
        "complications": "The remaining chemicals are unstable; vibration or mixing could cause toxic reactions",
        "things": "A sealed vial of an unknown substance that glows faintly in darkness",
        "places": "A blast-shielded alcove where the most dangerous experiments were conducted",
    },
    {
        "name": "Cistern Depths",
        "description": "A vast underground reservoir, its waters dark and cold, stone pillars rising from the depths.",
        "enemies": "An aquatic predator that has grown enormous in the lightless waters",
        "friends": "A diver who has found an underwater passage to a sealed section of the ruin",
        "complications": "The water level is unpredictable; tidal forces from deep below cause surges",
        "things": "Coins and offerings thrown into the cistern over centuries, glinting on the bottom",
        "places": "A narrow stone walkway along the cistern wall, just above the waterline",
    },
    {
        "name": "Warding Circle",
        "description": "Concentric rings of inscribed metal are set into the floor, their protective enchantments flickering.",
        "enemies": "An entity partially contained by the failing wards, testing the boundaries",
        "friends": "A sorcerer attempting to reinforce the wards before they collapse entirely",
        "complications": "Breaking the circle's continuity — even by stepping on a line — weakens the containment",
        "things": "A wardstone that can be used to repair one section of the failing circle",
        "places": "The exact center of the circle, where the contained entity's influence is paradoxically weakest",
    },
    {
        "name": "Ventilation Shaft",
        "description": "A vertical shaft with rusted iron rungs, carrying air — and sound — between the ruin's levels.",
        "enemies": "Climbing creatures that use the shaft as their highway between hunting grounds",
        "friends": "A trapped explorer who fell partway down and clings to a broken rung",
        "complications": "The rungs are corroded; each handhold must be tested or risk a fatal fall",
        "things": "A satchel snagged on a rung, dropped by a previous explorer",
        "places": "A maintenance alcove carved into the shaft wall, with a sealed access door",
    },
    {
        "name": "Sunken Library",
        "description": "Rows of stone shelves descend into murky water, their lower contents lost to flooding centuries ago.",
        "enemies": "An aquatic predator that has made the flooded stacks its hunting ground",
        "friends": "A scholar in a makeshift raft, fishing for readable tablets from the submerged shelves",
        "complications": "The water level is rising from a blocked outflow; the upper shelves will be submerged within hours",
        "things": "A waterproofed scroll case containing a complete map of the ruin's original layout",
        "places": "A mezzanine reading gallery still above water, its railing overlooking the drowned lower floor",
    },
    {
        "name": "Clockwork Foundry",
        "description": "Gears of every size line the walls and ceiling, some still turning in slow mechanical cycles powered by unknown means.",
        "enemies": "A partially assembled automaton that attacks with incomplete but deadly motions",
        "friends": "A clockmaker who has spent weeks understanding the gear patterns and can predict the machine cycles",
        "complications": "The gears periodically shift configuration, sealing some passages and opening others",
        "things": "A precision gear of impossible craftsmanship that could be worth a fortune to the right artificer",
        "places": "The winding chamber where a massive mainspring coils in the dark, still under tension",
    },
    {
        "name": "Spirit Prison",
        "description": "Translucent barriers of shimmering energy divide this chamber into cells, some still occupied by flickering forms.",
        "enemies": "A spirit that has partially escaped its containment, lashing out at anything living",
        "friends": "A bound spirit that offers information in exchange for release, its motives unclear",
        "complications": "The containment fields are failing in cascade; freeing one prisoner weakens all remaining cells",
        "things": "A warden's control rod that can reinforce or deactivate individual containment barriers",
        "places": "The central monitoring station where the status of each cell is displayed on a crystal panel",
    },
    {
        "name": "Mirror Maze",
        "description": "Polished metal panels create an endless labyrinth of reflections, designed to confuse and disorient intruders.",
        "enemies": "A creature that exists only in reflections, reaching through the mirrors to strike",
        "friends": "A trapped explorer who has been marking the real walls with chalk to find the exit",
        "complications": "Some mirrors show accurate reflections; others show different locations entirely, or different times",
        "things": "A mirror shard that always shows the viewer's back, regardless of angle",
        "places": "The maze's center, where all reflections converge on a single pedestal",
    },
    {
        "name": "Breeding Pit",
        "description": "Vats and tanks of clouded fluid fill this chamber, some cracked open, others still sealed with things moving inside.",
        "enemies": "Malformed creatures that have escaped the vats, aggressive and unpredictable",
        "friends": "A naturalist horrified by what was created here but fascinated by the techniques",
        "complications": "One of the sealed tanks is cracking; whatever is inside is large and nearly ready to emerge",
        "things": "A creator's logbook detailing the formulas used, written in clinical detachment",
        "places": "A drainage channel beneath the tanks where failed specimens were flushed away",
    },
    {
        "name": "Observatory",
        "description": "A domed chamber with a ceiling of dark crystal that still shows the stars, even deep underground.",
        "enemies": "A guardian construct that attacks anyone who touches the astronomical instruments",
        "friends": "An astronomer who has discovered the ceiling shows stars as they were millennia ago",
        "complications": "The star positions shown do not match the current sky; something has changed, and the implications are disturbing",
        "things": "A star chart etched on metal plates, showing constellations that no longer exist",
        "places": "The primary viewing platform with instruments that can focus the crystal ceiling on specific regions of sky",
    },
    {
        "name": "Soul Engine",
        "description": "A massive apparatus of metal and crystal dominates this chamber, conduits running from it in every direction like veins.",
        "enemies": "Spectral remnants trapped in the engine's workings, lashing out at those who disturb the machinery",
        "friends": "A horrified mystic who has determined the engine's purpose and wants it destroyed",
        "complications": "The engine is still partially active; destroying it might release what it contains, and what it contains may be terrible",
        "things": "A crystal core that pulses with captured life energy, warm and faintly screaming",
        "places": "The intake chamber where subjects were once placed, its restraints still functional",
    },
    {
        "name": "Trophy Hall",
        "description": "Mounted heads, preserved specimens, and display cases line this long gallery, chronicling conquests of a vanished master.",
        "enemies": "Preserved specimens that have been reanimated by lingering enchantments, jerking to life when approached",
        "friends": "A historian cataloguing the trophies, each one a clue to the ruin-builder's history",
        "complications": "Some trophies are of species still extant and territorial; their living kin may be nearby",
        "things": "A mounted weapon of exquisite quality displayed above the largest trophy",
        "places": "The final alcove, empty except for a plaque describing a trophy yet to be claimed",
    },
    {
        "name": "Collapsed Bridge",
        "description": "A stone bridge over a deep internal chasm has partially fallen, leaving a gap that must be crossed.",
        "enemies": "Creatures nesting on the bridge's underside that attack anyone attempting to cross",
        "friends": "A stranded explorer on the far side who has materials to help construct a temporary crossing",
        "complications": "The remaining bridge sections are unstable; weight must be distributed carefully or more will collapse",
        "things": "A grappling hook and silk rope left by a previous crosser, still anchored to the far side",
        "places": "A ledge beneath the bridge where a narrow path winds along the chasm wall",
    },
    {
        "name": "Underground River",
        "description": "A dark river flows through a carved channel, its current swift and its destination unknown.",
        "enemies": "Pale, eyeless fish grown to enormous size in the lightless waters, attracted by blood",
        "friends": "A ferryman with a flat-bottomed boat who charges passage and knows the river's branches",
        "complications": "The river forks ahead; one branch leads deeper into the ruin, the other to a waterfall into darkness",
        "things": "A sealed barrel floating in the current, its contents preserved and potentially valuable",
        "places": "A stone dock where boats were once moored, one ancient vessel still chained in place",
    },
    {
        "name": "Memory Well",
        "description": "A circular pool of silver liquid occupies the center of this chamber, showing scenes from the past to those who gaze into it.",
        "enemies": "A psychic parasite that feeds on the memories the well surfaces, growing stronger with each visitor",
        "friends": "A diviner using the well to research the ruin's history, willing to share discoveries",
        "complications": "The well draws out the viewer's own memories; prolonged gazing causes disorientation and identity confusion",
        "things": "A memory trapped in a crystal vial, viewable by anyone who holds it to their eye",
        "places": "An alcove with a stone chair positioned to face the well, worn smooth by centuries of use",
    },
    {
        "name": "Plague Ward",
        "description": "Rows of stone beds line this chamber, stained and scarred by whatever disease was treated here long ago.",
        "enemies": "Infectious remnants that have persisted in spore form, animating when the air is disturbed",
        "friends": "A physician studying ancient disease treatments, wearing protective wrappings and a filtered mask",
        "complications": "The ancient plague may still be viable; disturbing the beds risks exposure to something modern bodies cannot fight",
        "things": "A sealed medicine chest containing remedies that may still be potent",
        "places": "The apothecary annex where treatments were prepared, its shelves still lined with labeled jars",
    },
    {
        "name": "Slave Quarters",
        "description": "Cramped chambers with iron rings set into the walls, the marks of chains worn deep into the stone.",
        "enemies": "The spectral echoes of overseers, still enforcing order with phantom whips",
        "friends": "A descendant of the enslaved who has come seeking ancestral records and closure",
        "complications": "The quarters are trapped with mechanisms designed to prevent escape; they still function",
        "things": "A hidden cache of contraband carved into the wall behind a loose stone, left by a long-dead prisoner",
        "places": "A tunnel dug by hand over generations, leading partway to the surface before it was discovered and sealed",
    },
    {
        "name": "Golem Workshop",
        "description": "Stone and clay forms in various stages of completion stand on work platforms, tools and molds scattered around them.",
        "enemies": "A half-finished golem that activates erratically, following fragmentary instructions",
        "friends": "An artificer studying the construction techniques, hoping to repair rather than create",
        "complications": "The activation circle on the floor still functions; stepping into it with the wrong materials triggers unpredictable effects",
        "things": "A golem's command tablet, partially inscribed, that could control any golem keyed to this workshop",
        "places": "The kiln room where clay forms were fired, large enough to hold a giant",
    },
    {
        "name": "Drowning Chamber",
        "description": "A room designed to flood on command, its drains sealed and its inlet valves rusted but functional.",
        "enemies": "A trap keeper construct that activates the flooding mechanism when intruders are detected",
        "friends": "A previous victim clinging to a high shelf, half-drowned but alive",
        "complications": "The door seals are still airtight; if the chamber floods, escape requires finding the emergency release",
        "things": "The emergency release mechanism, visible but requiring a specific tool to operate",
        "places": "An air pocket near the ceiling where the stone is carved with handholds, a designed mercy",
    },
    {
        "name": "Mosaic Floor",
        "description": "An intricate floor mosaic depicts a map or diagram of incredible complexity, its tiles still vivid after millennia.",
        "enemies": "A guardian that activates when specific tiles are stepped on in the wrong sequence",
        "friends": "An artist tracing the mosaic's pattern, who has identified some of the depicted locations as real places",
        "complications": "The mosaic is a pressure-plate puzzle; the correct path grants access, the wrong one triggers traps",
        "things": "A bag of replacement tiles found near the wall, suggesting the mosaic was maintained and valued",
        "places": "The mosaic's depicted center point, which corresponds to a hidden room directly below",
    },
    {
        "name": "Wind Organ",
        "description": "Massive pipes of metal and stone line the walls, moaning as air moves through the ruin's corridors.",
        "enemies": "Sound-sensitive predators drawn to the pipes' vibrations, hunting by ear in the darkness",
        "friends": "A musician who has learned to play specific notes that open doors and disable traps",
        "complications": "Certain frequencies cause the stone to resonate dangerously; the wrong note could bring down the ceiling",
        "things": "A tuning key that adjusts the pipes, potentially changing what each note activates",
        "places": "The control console where the organist once sat, overlooking the pipe chamber from a protected gallery",
    },
    {
        "name": "Embalming Suite",
        "description": "Stone slabs, drainage channels, and shelves of preservation materials fill this mortuary chamber.",
        "enemies": "Preserved dead that have been imperfectly reanimated, lurching from their slabs",
        "friends": "A tomb robber who knows the dead here were buried with valuable grave goods",
        "complications": "The preservation chemicals are still active and toxic; spills cause chemical burns",
        "things": "An embalming tool of surgical precision, made from a metal that never dulls",
        "places": "The cold storage vault where the prepared dead were kept, its door sealed with a rusted lock",
    },
    {
        "name": "Signal Tower",
        "description": "A tall chamber designed to transmit messages, its beacon apparatus still intact though dark.",
        "enemies": "A creature that has laired at the tower's top, guarding the only access to the beacon",
        "friends": "A signaler from a distant settlement who believes the tower could be reactivated for communication",
        "complications": "Relighting the beacon would be visible for miles, attracting attention both welcome and otherwise",
        "things": "A codebook for the signal system, translating light patterns to messages",
        "places": "The beacon platform at the tower's summit, exposed to the sky through a retractable ceiling",
    },
    {
        "name": "Fungal Throne",
        "description": "A vast fungal organism has colonized this chamber entirely, its fruiting bodies forming grotesque parodies of furniture and architecture.",
        "enemies": "Fungal-controlled husks of previous explorers, their bodies serving as mobile extensions of the colony",
        "friends": "A mycologist who communicates with the fungal intelligence through chemical signals",
        "complications": "The fungus is semi-sentient and territorial; it blocks exits with rapid growth when threatened",
        "things": "A core sample of the fungal mass containing compounds with potent medicinal properties",
        "places": "The original chamber beneath the fungal growth, accessible through a gap in the organism's base",
    },
    {
        "name": "Armory Vault",
        "description": "Racks of ancient weapons and armor line the walls, most rusted to uselessness but a few preserved by enchantment.",
        "enemies": "Animated suits of armor that still follow their last order to guard the vault",
        "friends": "A weapons collector who has identified the few pieces worth salvaging",
        "complications": "Removing any item triggers a locking mechanism that seals the vault doors",
        "things": "A blade that gleams as though freshly forged, its edge untouched by time",
        "places": "The vault master's office behind a heavy door, containing an inventory ledger",
    },
    {
        "name": "Spore Cathedral",
        "description": "A vast vaulted chamber where bioluminescent mold has created the illusion of stained glass windows in the darkness.",
        "enemies": "Swarms of parasitic insects that breed in the mold and attack warm-blooded creatures",
        "friends": "A lost pilgrim who believes the chamber is genuinely holy and refuses to leave",
        "complications": "The mold is spreading to clothing and gear; prolonged stay means carrying the contamination onward",
        "things": "A collection plate from when this was a real cathedral, coins from a dozen dead civilizations",
        "places": "The pulpit, carved from a single stone and miraculously free of mold growth",
    },
    {
        "name": "Geothermal Vent",
        "description": "Scalding steam hisses from cracks in the floor, and the air is thick with mineral-laden moisture.",
        "enemies": "Heat-adapted vermin that nest in the warm crevices, swarming when disturbed",
        "friends": "An engineer studying the geothermal system, who has mapped the safe paths between vents",
        "complications": "The venting is irregular; a vent can go from dormant to lethal in seconds",
        "things": "Mineral deposits around the vents containing rare earth elements valuable to alchemists",
        "places": "A heat exchanger chamber where the ancients once harnessed the thermal energy",
    },
    {
        "name": "Glass Garden",
        "description": "Delicate sculptures of plants and animals crafted from colored glass fill this chamber, eerily lifelike.",
        "enemies": "A guardian that hurls glass shards with lethal precision, reforming them from the broken sculptures",
        "friends": "A glass-blower awed by the artistry, carefully studying the techniques used",
        "complications": "The glass is incredibly fragile; combat here destroys irreplaceable art and creates a floor of cutting shards",
        "things": "A glass flower that chimes a single pure note when held, functioning as a key somewhere in the ruin",
        "places": "A display case at the chamber's center containing the masterwork: a glass tree with crystal fruit",
    },
    {
        "name": "Map Room",
        "description": "A three-dimensional model of the surrounding region fills this chamber, carved in stone and inlaid with metal.",
        "enemies": "A territorial creature that has laired in the model's mountain range, treating it as its personal terrain",
        "friends": "A navigator who has realized the model shows features no longer visible on the surface",
        "complications": "The model shows locations that have been deliberately erased, suggesting someone wanted them forgotten",
        "things": "A marker pin of precious metal placed at a specific location on the model",
        "places": "The viewing gallery above the model, where observers once tracked troop movements or weather patterns",
    },
    {
        "name": "Resonance Chamber",
        "description": "A perfectly spherical room where even breathing creates overlapping echoes that build to disorienting intensity.",
        "enemies": "A sonic predator that uses the chamber's acoustics to stun prey with amplified shrieks",
        "friends": "A deaf explorer who navigates the chamber without difficulty, offering to guide others through",
        "complications": "Any combat in this room produces deafening reverberations; even speaking above a whisper causes pain",
        "things": "An acoustic dampener that creates a bubble of silence around its holder",
        "places": "The single dead spot in the room where sound does not amplify, marked by a worn circle on the floor",
    },
    {
        "name": "Irrigation Network",
        "description": "A complex system of channels, sluices, and aqueducts once distributed water throughout the complex.",
        "enemies": "Parasitic creatures that infest the water channels and attack anything that enters",
        "friends": "A plumber who has restored partial water flow and uses the channels for transportation",
        "complications": "Reopening one sluice gate floods another section; the system requires careful balance",
        "things": "A sluice key that controls water flow to multiple sections of the ruin",
        "places": "The master valve chamber where all channels can be observed and controlled from a single platform",
    },
    {
        "name": "Bone Weaver's Den",
        "description": "Thousands of bones have been arranged into intricate lattices and structures, crafted by something with inhuman patience.",
        "enemies": "The bone weaver itself, a creature that incorporates the bones of its kills into its ever-growing creation",
        "friends": "A trapped adventurer whose companions became part of the lattice, desperate to escape",
        "complications": "The bone structures are load-bearing; removing the wrong piece could collapse the ceiling",
        "things": "A skull with gemstone eyes, positioned at the lattice's focal point",
        "places": "A hollow at the lattice's center where the weaver rests, surrounded by its most recent additions",
    },
    {
        "name": "Furnace Heart",
        "description": "The ruin's central heating system, a massive furnace of dark metal that radiates residual warmth centuries after its last firing.",
        "enemies": "A fire elemental bound within the furnace, weakened but still dangerous when disturbed",
        "friends": "A metallurgist studying the furnace's alloys, which resist heat beyond anything modern smiths can achieve",
        "complications": "The furnace's fuel reservoirs still contain combustible material; a spark could reignite the entire system",
        "things": "A handful of the furnace's exotic fuel, a substance that burns hotter and longer than any known combustible",
        "places": "The stoking platform above the furnace mouth, connected by catwalks to the fuel storage bays",
    },
    {
        "name": "Petrified Congregation",
        "description": "Dozens of stone figures stand frozen mid-gesture in this hall, their expressions caught between prayer and terror.",
        "enemies": "A basilisk-spawn that lairs among the statues, adding to the congregation with its gaze",
        "friends": "A sculptor who believes some of the figures can be restored to flesh with the right solvent",
        "complications": "The petrification effect lingers in the air; prolonged exposure causes creeping numbness in the extremities",
        "things": "A vial of alchemical de-petrifier found clutched in a statue's hand, enough for one application",
        "places": "The altar at the hall's far end where the officiating priest stands frozen, arms raised over a stone basin",
    },
    {
        "name": "Temporal Eddy",
        "description": "Time flows unevenly through this chamber — dust motes hang motionless in some areas while plants grow and wither in seconds in others.",
        "enemies": "A predator that phases between time streams, appearing to teleport as it strikes from accelerated pockets",
        "friends": "A chronomancer trapped in a slow-time bubble, able to speak only one word per minute but possessing vital knowledge",
        "complications": "Stepping into the wrong temporal zone could age a limb decades in seconds or freeze a person for hours",
        "things": "A pendulum of dark metal that swings at a constant rate regardless of the surrounding time distortion",
        "places": "The chamber's exact center where all time streams converge at normal speed, marked by a worn circle of stability",
    },
    {
        "name": "Cocoon Gallery",
        "description": "Silk-like casings hang from the ceiling in dense clusters, some translucent enough to reveal humanoid shapes curled within.",
        "enemies": "The spinner — a massive arachnid creature that wraps its prey in preserving silk for later consumption",
        "friends": "A still-living victim cut free from a fresh cocoon, disoriented but grateful and knowledgeable about the ruin's upper levels",
        "complications": "The silk is incredibly adhesive; brushing against a cocoon risks becoming stuck, and struggling draws the spinner's attention",
        "things": "A bolt of the cocoon silk, cleaned and bundled — stronger than steel cable and lighter than linen",
        "places": "The spinner's central web, a vast radial construction spanning a vertical shaft between three levels of the ruin",
    },
    {
        "name": "Salt Labyrinth",
        "description": "Walls of compacted crystalline salt create a maze of blinding white corridors, the air painfully dry.",
        "enemies": "Desiccated husks of former explorers, preserved by the salt and animated by a malign will that permeates the mineral",
        "friends": "A merchant who knows the labyrinth leads to a salt deposit of extraordinary purity, worth a fortune in trade",
        "complications": "The salt draws moisture from everything — leather cracks, lips split, and wounds refuse to clot in the arid air",
        "things": "A salt crystal the size of a fist, perfectly clear, with something ancient and dark suspended at its core",
        "places": "A brine pool at the labyrinth's lowest point where the salt walls have dissolved into a knee-deep mineral bath",
    },
    {
        "name": "Whispering Pipes",
        "description": "Thousands of narrow tubes of ceramic and copper riddle the walls, carrying faint voices from elsewhere in the ruin.",
        "enemies": "A creature that mimics voices through the pipes, luring prey into ambush chambers with cries for help",
        "friends": "A spy who has learned to identify which pipes connect to which rooms, using them to eavesdrop on the ruin's other inhabitants",
        "complications": "Conversations held here are audible throughout the ruin's pipe network; nothing said in this room is private",
        "things": "A listening horn designed to fit over specific pipe openings, amplifying distant sounds to clarity",
        "places": "The switching hub where pipes from every section converge, allowing an operator to connect or disconnect any pair of rooms",
    },
    {
        "name": "Vitrified Barracks",
        "description": "The walls of this military quarter have been fused to glass by some catastrophic release of heat, preserving the garrison's final moments in silhouette.",
        "enemies": "Ember wraiths born from the soldiers who perished in the conflagration, radiating lethal heat",
        "friends": "An archaeologist documenting the vitrified shadows, who has pieced together what weapon was used and where it might still be",
        "complications": "The glass walls are razor-sharp where broken and structurally fragile; impacts send cascades of cutting shards across the room",
        "things": "A commanding officer's seal fused into the glass wall, recoverable with careful extraction and still recognized as authority by the ruin's lock-constructs",
        "places": "The armory at the barracks' core, its contents melted into a slag heap except for one sealed vault whose door glows faintly with protective wards",
    },
]
