"""Ruin environment tags for dungeon/ruin scene generation.

Each tag provides elements (enemies, friends, complications, things, places)
that scene.py combines to create emergent ruin exploration scenes. Tags draw
from the Latter Earth setting where ancient civilizations left behind vast
networks of ruins, underground complexes, and magical infrastructure.
"""

RUIN_TAGS = [
    {
        "name": "Collapsed Archive",
        "description": "Shelves of stone tablets and scroll cases line the walls, most shattered by the ceiling's partial collapse.",
        "enemies": "Vermin swarms nesting in the debris, aggressive when their lairs are disturbed",
        "friends": "A scholar trapped under rubble, alive but pinned and weakening",
        "complications": "The remaining ceiling is unstable; loud noise or vibration risks further collapse",
        "things": "An intact scroll case containing a readable document in an ancient tongue",
        "places": "A reading alcove miraculously untouched, its stone desk still bearing open tablets",
    },
    {
        "name": "Flooded Crypt",
        "description": "Black water fills this burial chamber to knee depth, disturbed coffins floating among the debris.",
        "enemies": "Waterlogged undead that rise silently from beneath the surface",
        "friends": "A treasure hunter clinging to a ledge above the waterline, too frightened to continue alone",
        "complications": "The water is rising slowly — a blocked drain somewhere is backing up",
        "things": "A sealed reliquary floating among the debris, its contents waterproof",
        "places": "A raised stone platform where the most important sarcophagus rests above the flood",
    },
    {
        "name": "Mechanical Chamber",
        "description": "Gears, pistons, and cables of an incomprehensible machine fill this room, some still clicking.",
        "enemies": "A malfunctioning automaton that attacks anything that moves within its patrol zone",
        "friends": "A tinkerer who has partially decoded the machine's purpose and needs help with a repair",
        "complications": "The machine is still partially active; touching the wrong component could trigger a dangerous cycle",
        "things": "A control lever that seems to govern some function deeper in the ruin",
        "places": "A maintenance crawlspace behind the machine, leading to another section of the complex",
    },
    {
        "name": "Fungal Garden",
        "description": "Luminescent fungi carpet the floor and walls, casting the chamber in eerie blue-green light.",
        "enemies": "Insectoid creatures that cultivate the fungi and attack intruders as threats to their crop",
        "friends": "An alchemist harvesting rare fungal specimens, willing to trade medicinal preparations",
        "complications": "Some fungi release paralytic spores when disturbed; the safe path is narrow",
        "things": "A cluster of rare medicinal fungi worth considerable coin to an apothecary",
        "places": "A deeper grotto where the fungi grow enormous, their caps forming a false ceiling",
    },
    {
        "name": "Obsidian Mirror",
        "description": "A massive polished obsidian surface dominates one wall, its reflection subtly wrong.",
        "enemies": "A creature that lurks behind the mirror, emerging to hunt when prey draws close",
        "friends": "A mystic studying the mirror's properties, believing it shows other places or times",
        "complications": "The mirror seems to show a slightly different version of the room — with something else in it",
        "things": "A silver frame around the mirror set with gemstones in a pattern that might be a key",
        "places": "The space directly before the mirror, where sound behaves strangely",
    },
    {
        "name": "Sacrificial Hall",
        "description": "A tiered amphitheater descends to a blood-stained altar at its center.",
        "enemies": "Cultists who have reconsecrated the altar and use the ruin for their ceremonies",
        "friends": "A prisoner awaiting sacrifice, bound and gagged on the lower tiers",
        "complications": "The altar radiates a palpable wrongness; lingering near it causes nausea and dread",
        "things": "A ceremonial blade of ancient make, still sharp and stained with old blood",
        "places": "A hidden preparation chamber behind the altar, accessible through a pivoting wall section",
    },
    {
        "name": "Crystal Vault",
        "description": "The walls of this chamber are lined with crystalline formations that refract light into rainbow patterns.",
        "enemies": "A crystal-armored creature that is nearly invisible against the glittering walls",
        "friends": "A trapped prospector who knows the crystals' value but cannot carry enough alone",
        "complications": "The crystals amplify sound painfully; combat here is deafening",
        "things": "A crystal lens that focuses light into a cutting beam when held at the right angle",
        "places": "A natural alcove where the crystals have grown into a throne-like formation",
    },
    {
        "name": "Sealed Ward",
        "description": "Heavy doors marked with warning glyphs stand partially open, their seals broken from within.",
        "enemies": "Whatever was imprisoned here, now loose in the surrounding chambers",
        "friends": "A warden-descendant who knows the sealing rituals but lacks the strength to perform them alone",
        "complications": "The ward's magical containment is failing; reality feels thin and wrong near the breach",
        "things": "A warden's key that can reactivate certain containment measures",
        "places": "The innermost cell, its walls covered in scratch marks and desperate inscriptions",
    },
    {
        "name": "Aqueduct Junction",
        "description": "Water channels from multiple directions converge here in a hub of ancient hydraulic engineering.",
        "enemies": "Aquatic predators that use the channels as highways through the ruin",
        "friends": "An engineer studying the water system, mapping the ruin's layout through its plumbing",
        "complications": "One channel is blocked; water pressure is building and may burst through",
        "things": "A valve wheel that controls water flow to different sections of the complex",
        "places": "A dry maintenance corridor running alongside the main channel",
    },
    {
        "name": "Bone Ossuary",
        "description": "The walls are constructed entirely from carefully arranged human bones, stacked floor to ceiling.",
        "enemies": "Undead assembled from the ossuary bones, collapsing and reforming endlessly",
        "friends": "A priest performing rites for the dead, trying to bring peace to the restless spirits",
        "complications": "Disturbing the bones triggers a cascading collapse of the wall sections",
        "things": "A skull marked with gold leaf and gems, clearly someone of great importance",
        "places": "A central chamber where a single intact skeleton sits on a chair, hands folded",
    },
    {
        "name": "Forge Level",
        "description": "Anvils, quenching troughs, and cold furnaces fill this industrial section of the ruin.",
        "enemies": "A fire elemental or golem bound to the forge, still following its last orders",
        "friends": "A smith who has rekindled one furnace and is producing simple tools for a nearby settlement",
        "complications": "Gas pockets in the forge vents; an open flame could trigger an explosion",
        "things": "An unfinished masterwork weapon on the anvil, needing only final tempering",
        "places": "The master smith's private workroom, its door sealed with a puzzle lock",
    },
    {
        "name": "Garden Atrium",
        "description": "A vast skylit chamber where plants have run wild, roots cracking the stone floor.",
        "enemies": "Predatory plants that have evolved in isolation, their vines quick and grasping",
        "friends": "A herbalist who has discovered medicinal species found nowhere else",
        "complications": "The root system has compromised the floor's integrity; sections may give way",
        "things": "Seeds of a plant thought extinct, viable if planted in the right conditions",
        "places": "A stone gazebo at the garden's center, overgrown but structurally sound",
    },
    {
        "name": "Echo Gallery",
        "description": "A long corridor where every sound repeats and amplifies, making stealth impossible.",
        "enemies": "Blind predators that navigate by echolocation, drawn to any noise",
        "friends": "A musician who has learned to use the echoes to map hidden passages",
        "complications": "Combat sounds attract every creature in adjacent chambers",
        "things": "A pair of wax earplugs enchanted to muffle sound while allowing speech",
        "places": "An acoustic dead spot where sound does not carry — a perfect hiding place",
    },
    {
        "name": "Gravity Well",
        "description": "A section where gravity pulls in the wrong direction, sending debris floating upward.",
        "enemies": "Creatures adapted to the inverted gravity that attack from unexpected angles",
        "friends": "An explorer tethered to a pillar, studying the anomaly with makeshift instruments",
        "complications": "The gravity shifts unpredictably; what's down becomes up without warning",
        "things": "A device at the anomaly's center that might be causing the distortion",
        "places": "A ceiling that has become a floor, complete with furniture bolted to it",
    },
    {
        "name": "Painted Hall",
        "description": "Every surface is covered in vivid murals depicting the daily life of the ruin's former inhabitants.",
        "enemies": "Guardians triggered by anyone who damages the murals",
        "friends": "An artist carefully copying the murals before they fade completely",
        "complications": "The murals contain a hidden message visible only by torchlight from a specific angle",
        "things": "Pigments used in the murals, still vivid after millennia — extremely valuable",
        "places": "A concealed door painted to blend seamlessly with the surrounding mural",
    },
    {
        "name": "Prison Block",
        "description": "Rows of iron-barred cells line a central corridor, some still locked, others torn open.",
        "enemies": "The descendants of the original prisoners, gone feral over generations of isolation",
        "friends": "A recent captive locked in a cell by the current inhabitants of the ruin",
        "complications": "The locking mechanism is connected to a trap system; opening one cell triggers another",
        "things": "A prisoner's journal scratched into the wall, describing the ruin's layout",
        "places": "The warden's office at the corridor's end, with keys still hanging on the wall",
    },
    {
        "name": "Throne Room",
        "description": "A grand chamber dominated by a stone throne on a raised dais, its former glory faded but evident.",
        "enemies": "A powerful creature that has claimed the throne room as its lair",
        "friends": "A claimant to the ruined domain seeking allies to help secure the throne",
        "complications": "The throne is trapped — sitting in it activates ancient defensive systems",
        "things": "A crown resting on the throne, tarnished but set with stones of evident value",
        "places": "A hidden passage behind the throne leading to private chambers",
    },
    {
        "name": "Refuse Pit",
        "description": "A deep shaft where the ruin's inhabitants once dumped waste, now a stratified archaeological record.",
        "enemies": "A massive scavenger creature that nests in the accumulated refuse",
        "friends": "A treasure-sifter who has found valuable discards and knows the pit's safe ledges",
        "complications": "The refuse produces methane; bringing fire here risks a devastating explosion",
        "things": "A discarded item of surprising value buried in the muck",
        "places": "A ledge halfway down the pit with access to a sealed side passage",
    },
    {
        "name": "Alchemical Laboratory",
        "description": "Glass vessels, metal retorts, and stone basins crowd this chamber, some still containing liquids.",
        "enemies": "A creature spawned or mutated by the ancient chemicals still active in the lab",
        "friends": "An alchemist who has identified several still-potent reagents",
        "complications": "The remaining chemicals are unstable; vibration or mixing could cause toxic reactions",
        "things": "A sealed vial of an unknown substance that glows faintly in darkness",
        "places": "A blast-shielded alcove where the most dangerous experiments were conducted",
    },
    {
        "name": "Cistern Depths",
        "description": "A vast underground reservoir, its waters dark and cold, stone pillars rising from the depths.",
        "enemies": "An aquatic predator that has grown enormous in the lightless waters",
        "friends": "A diver who has found an underwater passage to a sealed section of the ruin",
        "complications": "The water level is unpredictable; tidal forces from deep below cause surges",
        "things": "Coins and offerings thrown into the cistern over centuries, glinting on the bottom",
        "places": "A narrow stone walkway along the cistern wall, just above the waterline",
    },
    {
        "name": "Warding Circle",
        "description": "Concentric rings of inscribed metal are set into the floor, their protective enchantments flickering.",
        "enemies": "An entity partially contained by the failing wards, testing the boundaries",
        "friends": "A sorcerer attempting to reinforce the wards before they collapse entirely",
        "complications": "Breaking the circle's continuity — even by stepping on a line — weakens the containment",
        "things": "A wardstone that can be used to repair one section of the failing circle",
        "places": "The exact center of the circle, where the contained entity's influence is paradoxically weakest",
    },
    {
        "name": "Ventilation Shaft",
        "description": "A vertical shaft with rusted iron rungs, carrying air — and sound — between the ruin's levels.",
        "enemies": "Climbing creatures that use the shaft as their highway between hunting grounds",
        "friends": "A trapped explorer who fell partway down and clings to a broken rung",
        "complications": "The rungs are corroded; each handhold must be tested or risk a fatal fall",
        "things": "A satchel snagged on a rung, dropped by a previous explorer",
        "places": "A maintenance alcove carved into the shaft wall, with a sealed access door",
    },
]
