"""Wilderness environment tags for scene generation.

Each tag provides elements (enemies, friends, complications, things, places)
that scene.py combines to create emergent exploration scenes. Tags evoke the
Latter Earth setting: a post-apocalyptic fantasy world built on the ruins of
prior civilizations, where ancient magic and mundane survival coexist.
"""

WILDERNESS_TAGS = [
    {
        "name": "Blighted Grove",
        "description": "Trees here grow twisted and dark, their bark weeping an oily sap that stains the earth.",
        "enemies": "A pack of feral beasts warped by the blight, eyes gleaming with unnatural hunger",
        "friends": "A wandering herbalist gathering samples of the corruption for study",
        "complications": "The blight is spreading visibly; staying too long risks contamination",
        "things": "A cracked crystal embedded in the largest tree, pulsing with faint light",
        "places": "A clearing where nothing grows, the soil fused to black glass",
    },
    {
        "name": "Ancient Road",
        "description": "A perfectly straight road of fitted stone stretches across the landscape, built by hands long forgotten.",
        "enemies": "Bandits using the road as a hunting ground for lone travelers",
        "friends": "A merchant caravan grateful for company on the dangerous stretch",
        "complications": "Sections of the road have collapsed into sinkholes revealing tunnels below",
        "things": "Carved milestones with distances to cities that no longer exist",
        "places": "A ruined waystation with a still-functioning cistern",
    },
    {
        "name": "Singing Stones",
        "description": "Tall standing stones emit a low harmonic hum when the wind passes through them.",
        "enemies": "A territorial creature that has made its lair among the stones",
        "friends": "A scholar documenting the tonal patterns, believing they encode a message",
        "complications": "The harmonics intensify at night, attracting dangerous predators",
        "things": "A tuning fork of unknown metal that resonates with the stones",
        "places": "The central ring where the harmonics converge into a single clear note",
    },
    {
        "name": "Flooded Lowland",
        "description": "Seasonal rains have turned this low valley into a shallow marsh of mud and standing water.",
        "enemies": "Amphibious predators lurking beneath the murky water",
        "friends": "A fishing family in a stilted shelter willing to share their catch",
        "complications": "The water is rising steadily and may soon cut off the only dry path",
        "things": "The top of a buried structure visible just above the waterline",
        "places": "An island of dry ground crowned by a massive dead tree",
    },
    {
        "name": "Ember Waste",
        "description": "The ground here is warm to the touch, and thin smoke rises from cracks in the earth.",
        "enemies": "Fire-adapted lizards the size of dogs that hunt in coordinated packs",
        "friends": "A prospector extracting heat-forged minerals from the vents",
        "complications": "Sudden gouts of flame erupt from the ground without warning",
        "things": "A vein of glass-like mineral formed by extreme underground heat",
        "places": "A natural hot spring surrounded by mineral deposits in vivid colors",
    },
    {
        "name": "Bone Field",
        "description": "The remains of enormous creatures litter this plain, their ribcages large enough to shelter under.",
        "enemies": "Scavengers that fiercely defend the bones as their territory",
        "friends": "A nomad band that camps in the shelter of a massive skull",
        "complications": "Something is killing creatures here regularly — the bones are fresh beneath the old",
        "things": "A tooth as long as a sword, carved with tiny script in an unknown language",
        "places": "A complete skeleton arched over the trail like a gateway",
    },
    {
        "name": "Mist Hollow",
        "description": "A perpetual fog fills this depression, limiting visibility to a few paces.",
        "enemies": "Predators that have adapted to hunt by sound in the dense fog",
        "friends": "A lost traveler calling out, desperate for a guide through the mist",
        "complications": "The mist distorts direction; compasses spin and landmarks vanish",
        "things": "A lantern that burns without fuel, found hanging from a dead branch",
        "places": "A stone bridge over a chasm invisible until you nearly step into it",
    },
    {
        "name": "Skyfall Crater",
        "description": "A vast circular depression marks where something fell from the heavens in ages past.",
        "enemies": "Opportunistic raiders camped on the crater rim, ambushing those who descend",
        "friends": "An astronomer from a distant city studying the impact site",
        "complications": "Metal objects behave strangely near the crater center — weapons pull toward the ground",
        "things": "Shards of a strange dark metal scattered across the crater floor",
        "places": "The crater center, where a pool of unnaturally still water reflects no sky",
    },
    {
        "name": "Thornwall",
        "description": "A barrier of thorny vegetation stretches as far as the eye can see, impenetrable and ancient.",
        "enemies": "Territorial vine-creatures that animate from the thornwall when disturbed",
        "friends": "A guide who knows a hidden passage through the barrier",
        "complications": "The thorns are mildly venomous; scratches cause fever and disorientation",
        "things": "A preserved corpse entangled in the thorns, its pack still intact",
        "places": "A natural arch in the thornwall where the vines have grown into a tunnel",
    },
    {
        "name": "Salt Flat",
        "description": "A blinding white expanse of crystallized salt stretches to the horizon under a merciless sun.",
        "enemies": "A salt devil pack hunting across the flat, camouflaged against the white ground",
        "friends": "Salt harvesters from a nearby community working the edges of the flat",
        "complications": "The crust is thin in places; breaking through reveals corrosive brine below",
        "things": "A perfectly preserved ancient artifact encased in salt crystal",
        "places": "A salt pillar formation that provides the only shade for miles",
    },
    {
        "name": "Petrified Forest",
        "description": "Stone trees stand in silent rows, turned to rock by some ancient catastrophe.",
        "enemies": "A stone-skinned predator that blends perfectly with the petrified trunks",
        "friends": "A stonemason harvesting petrified wood for a wealthy patron",
        "complications": "The petrification effect may still be active in places — flesh touching bare stone tingles",
        "things": "A petrified bird mid-flight, wings spread, impossibly balanced on a branch",
        "places": "A hollow in a massive petrified trunk, large enough to camp inside",
    },
    {
        "name": "Witch-Light Fen",
        "description": "Ghostly lights drift over the bog at night, and the locals refuse to enter after dark.",
        "enemies": "Bog-drowned undead that rise from the peat when the lights appear",
        "friends": "A hedge witch who harvests rare plants from the fen by day",
        "complications": "The safe paths shift with the seasons; yesterday's trail is today's drowning pool",
        "things": "A preserved offering to a forgotten god, wrapped in waxed cloth",
        "places": "A sunken temple half-submerged in black water, its altar still above the surface",
    },
    {
        "name": "Wind-Carved Canyon",
        "description": "Millennia of wind have sculpted this canyon into impossible shapes and howling passages.",
        "enemies": "Flying predators that nest on the canyon walls and dive on travelers below",
        "friends": "A hermit who has mapped the canyon's wind patterns and safest routes",
        "complications": "Wind funnels through certain passages with enough force to knock a person down",
        "things": "Ancient carvings revealed by erosion, depicting scenes of a vanished people",
        "places": "A natural amphitheater where whispers carry perfectly from wall to wall",
    },
    {
        "name": "Fungal Bloom",
        "description": "Enormous mushrooms tower overhead, their caps blocking the sun and releasing clouds of spores.",
        "enemies": "Insectoid creatures the size of dogs that farm and defend the fungal colony",
        "friends": "A forager who knows which fungi are edible and which are lethal",
        "complications": "Breathing the spores without protection causes hallucinations within hours",
        "things": "A luminescent fungus that glows bright enough to read by",
        "places": "A hollow beneath a massive mushroom cap, dry and warm from the organism's heat",
    },
    {
        "name": "Iron Rain Scar",
        "description": "The ground is pockmarked with craters and littered with rusted metal fragments from a skyfall of iron.",
        "enemies": "Rust-colored predators that have adapted to the ferrous terrain",
        "friends": "Scrap-metal traders picking through the debris for salvageable pieces",
        "complications": "Lightning strikes here with alarming frequency, drawn by the metal deposits",
        "things": "A chunk of meteoric iron, star-forged and suitable for a master smith",
        "places": "The largest crater, now a rust-stained pond circled by twisted metal spires",
    },
    {
        "name": "Whispering Grassland",
        "description": "Tall grass stretches endlessly, swaying in patterns that seem deliberate and directed.",
        "enemies": "Ambush predators hidden in the tall grass, invisible until they strike",
        "friends": "A nomadic herder whose animals know the safe paths through the grass",
        "complications": "The grass conceals sinkholes and old foundations; footing is treacherous",
        "things": "A wind chime made of bone, hanging from a lone tree",
        "places": "A stone circle where the grass refuses to grow, the bare earth black and hard",
    },
    {
        "name": "Crystal Seep",
        "description": "Mineral-laden water rises from underground, depositing brilliant crystal formations across the rocks.",
        "enemies": "Creatures drawn to the crystals that defend their territory with savage intensity",
        "friends": "A jeweler carefully extracting small crystals for sale in distant markets",
        "complications": "The crystals are beautiful but sharp as razors; moving carelessly draws blood",
        "things": "A crystal formation that has grown around a humanoid skeleton, encasing it perfectly",
        "places": "A grotto where crystal stalactites chime in the draft like a carillon",
    },
    {
        "name": "Thunder Ridge",
        "description": "A high ridgeline where storms gather with unnatural frequency and violence.",
        "enemies": "A beast that hunts during storms, using thunder to mask its approach",
        "friends": "A weather-reader who predicts storms and sells safe passage windows",
        "complications": "A storm is building now; crossing the ridge means racing the lightning",
        "things": "A lightning-fused sand sculpture, glass fingers reaching skyward",
        "places": "A cave system in the ridge face, dry but echoing with thunder",
    },
    {
        "name": "Sunken Garden",
        "description": "A terraced depression where plants grow in impossible abundance, fed by an underground spring.",
        "enemies": "A territorial guardian beast that has claimed the garden as its hunting ground",
        "friends": "A reclusive cultivator who tends the rarest plants and trades for supplies",
        "complications": "The abundance attracts constant animal activity; something large visits at night",
        "things": "A medicinal plant of extreme rarity, worth a fortune to the right buyer",
        "places": "The spring source, a clear pool surrounded by ancient carved channels",
    },
    {
        "name": "Ash Dunes",
        "description": "Dunes of volcanic ash stretch across the landscape, soft and shifting underfoot.",
        "enemies": "Burrowing predators that move through the ash like fish through water",
        "friends": "Ash-sailors in a wind-driven sled who offer passage across the waste",
        "complications": "A tremor loosens the ash; a minor avalanche threatens to bury the trail",
        "things": "A glass bead necklace from a civilization buried beneath the ash",
        "places": "The top of a buried tower protruding from the ash, its window a dark invitation",
    },
    {
        "name": "Warden Trees",
        "description": "Massive ancient trees grow in a deliberate circle, their canopy forming a natural dome.",
        "enemies": "Outlaws who have fortified the tree ring as a hidden base",
        "friends": "A druid-like keeper who maintains the trees and shares forest knowledge",
        "complications": "The trees are sacred to a local community; trespassing invites retribution",
        "things": "A heartwood tablet carved with a map of the surrounding region in exquisite detail",
        "places": "The hollow center of the largest tree, a natural chamber three stories tall",
    },
    {
        "name": "Glass Lake",
        "description": "A perfectly still lake whose surface reflects like a mirror, undisturbed even by wind.",
        "enemies": "Something large moves beneath the surface, visible only as a dark shadow",
        "friends": "A hermit fisher who warns travelers about the lake's dangers",
        "complications": "The lake's edge is treacherously smooth; the water is deceptively deep",
        "things": "A sealed jar on the lakebed, visible through the crystal-clear water",
        "places": "A small island at the lake's center, reachable by a submerged stone causeway",
    },
    {
        "name": "Amber Fields",
        "description": "Vast stretches of petrified resin coat the ground like frozen honey, trapping insects and small creatures from ages past.",
        "enemies": "Predatory beetles the size of shields, drawn to vibrations in the amber crust",
        "friends": "A naturalist cataloguing the preserved specimens for a distant academy",
        "complications": "The amber is softening in the heat; stepping carelessly risks becoming mired",
        "things": "A perfectly preserved flower encased in amber, its species long extinct",
        "places": "A depression where the amber has pooled deep, revealing shadowy shapes within",
    },
    {
        "name": "Verdant Ruin",
        "description": "The skeleton of a massive structure rises from the jungle, strangled by vines and crowned with trees.",
        "enemies": "A troop of territorial apes that have claimed the upper levels as their domain",
        "friends": "A cartographer sketching the ruin's outline, hoping to identify its original purpose",
        "complications": "The vegetation conceals unstable floors; one wrong step means a two-story fall",
        "things": "A stone tablet pried loose by roots, its inscription partially legible",
        "places": "The rooftop canopy where the trees have formed a second forest above the ruin",
    },
    {
        "name": "Fossil Beach",
        "description": "A shoreline of dark stone embedded with the spiral shells and strange bones of creatures from a prior age.",
        "enemies": "Tidal predators that surge inland with each wave, retreating before they can be cornered",
        "friends": "A collector who trades fossil specimens to scholars and pays well for unusual finds",
        "complications": "The tide is coming in fast; the beach will be submerged within the hour",
        "things": "A fossilized skull of something enormous, half-exposed by recent erosion",
        "places": "A sea cave revealed at low tide, its walls glittering with mineral deposits",
    },
    {
        "name": "Sulfur Springs",
        "description": "Yellow-crusted vents belch acrid steam, and the stench of brimstone hangs heavy in the still air.",
        "enemies": "A colony of heat-loving reptiles nesting in the warm mud around the vents",
        "friends": "A bathhouse keeper who channels the hot water and offers rest to travelers",
        "complications": "The ground is thin over boiling pools; a misstep means scalding immersion",
        "things": "Crystals of pure sulfur, valuable for alchemical preparations",
        "places": "A natural basin of hot mineral water, surrounded by colorful bacterial mats",
    },
    {
        "name": "Moonlit Glade",
        "description": "Silver-leafed trees ring a clearing where the moonlight falls with unnatural intensity, even on cloudy nights.",
        "enemies": "Nocturnal hunters that stalk the glade's edge, afraid to enter but willing to ambush those who leave",
        "friends": "A seer who reads omens in the patterns of moonlight on the silver leaves",
        "complications": "The glade exerts a soporific influence; those who rest here sleep deeply and dream vividly",
        "things": "A silver acorn that glows faintly, warm to the touch",
        "places": "The exact center of the glade, where a flat stone serves as an ancient altar",
    },
    {
        "name": "Carrion Pit",
        "description": "A natural sinkhole where dead things collect, drawing scavengers and a pervasive stench of decay.",
        "enemies": "A massive carrion-feeder that guards the pit as its personal larder",
        "friends": "A trapper who uses the pit's edge to set snares for the scavengers drawn here",
        "complications": "The pit walls are slick with organic residue; falling in means a difficult climb out",
        "things": "A partially digested satchel containing coins and a sealed letter",
        "places": "A ledge partway down the pit where bones have accumulated into a false floor",
    },
    {
        "name": "Frozen Lake",
        "description": "A lake locked under thick ice even in warm seasons, its surface cracked and groaning with mysterious pressure.",
        "enemies": "A predator that hunts from beneath the ice, slamming upward to break through under prey",
        "friends": "An ice-fisher who knows which sections are safe to cross and which are deadly thin",
        "complications": "The ice is fracturing; loud sounds or heavy impacts could shatter entire sections",
        "things": "Something large and dark visible through the ice, frozen in place far below",
        "places": "A fishing camp on the shore with a warm fire and a view across the frozen expanse",
    },
    {
        "name": "Lava Tubes",
        "description": "Hollow tunnels left by ancient lava flows snake beneath the volcanic terrain, their walls smooth and glassy.",
        "enemies": "A pack of eyeless cave predators that navigate the tubes by heat-sense",
        "friends": "A miner extracting obsidian from the tube walls, willing to share knowledge of the passages",
        "complications": "Some tubes still carry volcanic gases; an unventilated stretch could be lethal",
        "things": "A natural obsidian blade, sharper than steel, formed by the cooling lava",
        "places": "A cathedral-sized chamber where multiple tubes converge, lit by faintly glowing minerals",
    },
    {
        "name": "Old Battlefield",
        "description": "Rusted weapons and scattered bones mark a forgotten conflict, the earth still scarred by war.",
        "enemies": "Restless spirits of the fallen that manifest as twilight approaches",
        "friends": "A gravedigger hired by a distant lord to recover an ancestor's remains",
        "complications": "Unexploded alchemical ordnance lies buried in the churned earth, unstable after centuries",
        "things": "A battle standard preserved by enchantment, its colors still vivid",
        "places": "A command post dug into a hillside, its maps and orders still pinned to a rotting table",
    },
    {
        "name": "Spider Forest",
        "description": "Webs drape every surface in thick curtains, and the trees themselves seem wrapped in silk cocoons.",
        "enemies": "Giant spiders that drop silently from the canopy, wrapping prey before it can react",
        "friends": "A silk-harvester who has learned to move through the forest without triggering the webs",
        "complications": "The webs are nearly invisible in dim light and incredibly adhesive; struggling only entangles further",
        "things": "A cocoon containing the preserved gear of a previous traveler, still usable",
        "places": "A clearing kept web-free by a colony of fire ants, a precarious safe haven",
    },
    {
        "name": "Crystal Cave",
        "description": "A cavern entrance bristles with translucent crystals that hum faintly when touched, resonating with unknown energy.",
        "enemies": "A territorial beast that has laired in the cave, its hide embedded with crystal shards",
        "friends": "A gem-cutter seeking specimens of a specific crystal formation for a commission",
        "complications": "The crystals amplify and distort sound, making it impossible to tell where noises originate",
        "things": "A crystal cluster that vibrates at a frequency that opens a concealed passage deeper inside",
        "places": "An inner chamber where the crystals grow large as pillars and glow with their own light",
    },
    {
        "name": "Raptor Cliffs",
        "description": "Sheer cliffs rise above the landscape, home to enormous birds of prey that circle endlessly overhead.",
        "enemies": "Nesting raptors that attack anything approaching their eyries with diving fury",
        "friends": "A falconer attempting to capture a young raptor for training, needing a distraction",
        "complications": "The only path forward runs along a narrow ledge beneath the nesting sites",
        "things": "An enormous feather, iridescent and as long as a forearm, prized by fletchers",
        "places": "A wind-sheltered alcove in the cliff face where ancient hand-prints mark the stone",
    },
    {
        "name": "Tar Seep",
        "description": "Black pitch bubbles up from the earth in slow, viscous pools that trap the unwary.",
        "enemies": "Predators that lurk at the tar's edge, waiting for prey mired in the sticky pools",
        "friends": "Tar-workers harvesting the pitch for waterproofing and trade, experienced with the hazards",
        "complications": "The tar pools shift and new ones appear without warning; yesterday's safe ground is today's trap",
        "things": "The bones of an enormous beast protruding from the tar, something valuable glinting between its ribs",
        "places": "A solidified tar island in the center of the largest pool, reachable only by a precarious log bridge",
    },
    {
        "name": "Mirage Flats",
        "description": "Heat shimmers dance across this barren expanse, conjuring phantom lakes and distant towers that dissolve upon approach.",
        "enemies": "Desert stalkers that use the heat distortion to approach unseen until they are upon their prey",
        "friends": "A caravan guide who navigates by star-position rather than landmarks, immune to the mirages",
        "complications": "The mirages are not entirely natural; some show real places, but reaching them requires knowing which",
        "things": "A lens of smoky glass that, when looked through, dispels the mirages and reveals the true terrain",
        "places": "An actual oasis hidden among the false ones, its existence a closely guarded secret",
    },
    {
        "name": "Howling Pass",
        "description": "A narrow mountain pass where the wind screams between the peaks, carrying voices that might not be the wind.",
        "enemies": "Mountain predators that use the constant noise to mask their approach from all directions",
        "friends": "A pass warden who maintains trail markers and shelters for travelers",
        "complications": "A rockslide has partially blocked the pass; the detour adds days or the rubble must be climbed",
        "things": "A cairn of stacked stones left by countless travelers, with offerings tucked between the rocks",
        "places": "A wind-shadow behind a massive boulder where a traveler can rest and hear themselves think",
    },
    {
        "name": "Sinking Meadow",
        "description": "A beautiful meadow of wildflowers conceals a treacherous bog; the ground quakes underfoot like a living thing.",
        "enemies": "Bog worms that sense vibrations and erupt from below to drag prey under",
        "friends": "A shepherd whose flock grazes the firm edges, who knows which flowers mark safe ground",
        "complications": "A recent traveler is trapped waist-deep and sinking slowly, calling for help",
        "things": "A gnarled staff driven into the ground as a warning marker, carved with directions in an old tongue",
        "places": "A raised hummock of solid ground at the meadow's center, crowned by a lone dead oak",
    },
    {
        "name": "Burned Expanse",
        "description": "A recent wildfire has left this stretch blackened and smoking, the charred skeletons of trees still standing.",
        "enemies": "Displaced predators driven from their territories by the fire, hungry and agitated",
        "friends": "A fire-watcher tracking the blaze's origin, suspecting arson rather than lightning",
        "complications": "Hot spots and smoldering roots make the ground unpredictable; flames can reignite without warning",
        "things": "A cache of supplies buried before the fire, its marker post now ash but the goods intact below",
        "places": "A stream bed where the fire jumped, leaving a narrow corridor of green amid the devastation",
    },
    {
        "name": "Echo Gorge",
        "description": "A deep, narrow gorge where every sound bounces endlessly between the walls, layering into disorienting cacophony.",
        "enemies": "Cliff-dwelling ambushers that hurl stones from the rim, the echoes masking their positions",
        "friends": "A courier who uses the gorge as a shortcut and knows the acoustic tricks to navigate it",
        "complications": "The echoes make communication impossible at anything above a whisper; coordination in danger is difficult",
        "things": "Petroglyphs carved into the gorge walls at water level, visible only when the stream is low",
        "places": "A natural bridge spanning the gorge at its narrowest point, worn smooth by centuries of crossing",
    },
    {
        "name": "Worm Tunnels",
        "description": "Enormous bore-holes riddle the hillside, carved by some vast burrowing creature long ago or perhaps not so long.",
        "enemies": "A lesser burrower that has claimed the tunnels, collapsing passages to trap prey",
        "friends": "A surveyor mapping the tunnel network for a settlement that wants to use them for shelter",
        "complications": "Fresh bore-marks suggest the original digger may still be active somewhere in the network",
        "things": "A seam of valuable ore exposed by the tunneling, easily accessible from the passage wall",
        "places": "A chamber where multiple tunnels converge, the walls polished smooth by the creature's passage",
    },
    {
        "name": "Pilgrim's Road",
        "description": "An ancient path marked by weathered shrines, still walked by devotees traveling to a holy destination.",
        "enemies": "Bandits disguised as pilgrims who prey on the faithful and their offerings",
        "friends": "A pilgrim with stories of distant lands and a willingness to share provisions",
        "complications": "The road passes through territory claimed by a hostile group that demands tribute for passage",
        "things": "A pilgrim's token left at a shrine, said to grant safe passage in certain communities",
        "places": "A wayside shrine with a spring, a traditional resting point where pilgrims share news",
    },
    {
        "name": "Rust Marsh",
        "description": "Iron-rich water stains everything red-orange in this marsh, and the tang of metal hangs in the humid air.",
        "enemies": "Iron-scaled reptiles that blend perfectly with the rust-colored water and reeds",
        "friends": "A bog-iron smelter who extracts metal from the marsh water using traditional methods",
        "complications": "The iron content makes the water undrinkable; fresh water must be carried in or found elsewhere",
        "things": "A corroded but recognizable weapon jutting from the muck, its hilt still above water",
        "places": "A smelter's hut on stilts over the marsh, connected to shore by a rickety boardwalk",
    },
    {
        "name": "Skybridge Remnant",
        "description": "The broken arc of an impossibly high bridge stretches between two cliff faces, its far end shattered and gone.",
        "enemies": "Nesting creatures on the bridge's underside that attack anyone who sets foot on the span",
        "friends": "An engineer studying the bridge's construction, marveling at techniques beyond modern capability",
        "complications": "The bridge sways in high wind and sections of the surface have crumbled away, leaving gaps",
        "things": "A builder's plaque at the bridge's anchor point, inscribed in a language that predates all known tongues",
        "places": "A maintenance alcove built into the bridge's support pillar, accessible by a corroded ladder",
    },
    {
        "name": "Spore Wastes",
        "description": "A flat, dusty expanse where clouds of fungal spores drift on the wind like pale fog.",
        "enemies": "Fungal-infected animals that spread contamination through bites and scratches",
        "friends": "A masked herbalist collecting rare spores for medicinal use, equipped with protective gear",
        "complications": "Without face covering, the spores cause coughing, disorientation, and eventually fungal infection",
        "things": "A respirator mask of ancient make, still functional, found on a long-dead traveler",
        "places": "A rocky outcrop above the spore layer where the air is clear and camp can be made safely",
    },
    {
        "name": "Glassfield",
        "description": "The ground here has been fused to smooth glass by some unimaginable ancient heat, reflecting the sky like a dark mirror.",
        "enemies": "Scavenging beasts that cross the glass at night, their claws clicking audibly for miles",
        "friends": "A glass-knapper who harvests the material for tools and arrowheads of exceptional sharpness",
        "complications": "The glass is treacherously slick when wet; rain turns the field into an impassable skating surface",
        "things": "A bubble in the glass containing a perfectly preserved artifact from before the cataclysm",
        "places": "A crater in the glassfield's center where the glass is thickest, with shapes visible deep below",
    },
    {
        "name": "Titan's Bones",
        "description": "Colossal stone limbs and torso fragments lie half-buried across the landscape, remnants of a statue or a being beyond comprehension.",
        "enemies": "A cult that worships the remains and attacks anyone who approaches without proper obeisance",
        "friends": "An antiquarian measuring and sketching the fragments, trying to reconstruct what the titan looked like",
        "complications": "The stone radiates a low vibration that causes headaches and unease; prolonged exposure brings nightmares",
        "things": "A finger-bone of the titan, small enough to carry but carved with microscopic text",
        "places": "The hollow eye socket of the titan's fallen head, large enough to shelter a dozen people",
    },
    {
        "name": "Stormbreak Coast",
        "description": "A battered shoreline where storms arrive with supernatural regularity, smashing ships and reshaping the coast.",
        "enemies": "Wreckers who set false lights to lure ships onto the rocks and plunder the remains",
        "friends": "A lighthouse keeper who maintains the only true beacon on this stretch of coast",
        "complications": "A storm is building offshore; within hours the coast will be impassable",
        "things": "Fresh wreckage washing ashore, including sealed cargo containers from a merchant vessel",
        "places": "A sea cave above the tide line where shipwreck survivors have scratched tally marks on the walls",
    },
    {
        "name": "Wandering Stones",
        "description": "Massive boulders sit in this flat valley, leaving long furrows behind them as though they move when no one watches.",
        "enemies": "A territorial predator that uses the stones as cover, circling prey patiently",
        "friends": "A philosopher-naturalist studying the stones' movement, convinced they follow a pattern",
        "complications": "The stones move unpredictably; making camp near one risks being crushed in the night",
        "things": "A smaller stone that vibrates gently when placed on the ground, seemingly pulled toward the others",
        "places": "The convergence point where the furrows all lead, a depression where several stones have gathered",
    },
    {
        "name": "Canopy Sea",
        "description": "The forest canopy is so dense and continuous that travel occurs on the intertwined branches above, the ground invisible below.",
        "enemies": "Arboreal predators that swing through the canopy with terrifying speed",
        "friends": "A tree-dwelling community connected by rope bridges, willing to host respectful travelers",
        "complications": "The branches thin out ahead; crossing requires leaping gaps or descending to the dangerous forest floor",
        "things": "A nest containing iridescent eggs of a rare canopy bird, valuable to collectors",
        "places": "A platform village built where several massive trees interlock, high above the world",
    },
    {
        "name": "Blood Thorn Thicket",
        "description": "Crimson-thorned bushes grow in impenetrable tangles, their barbs dripping a sap that burns like acid.",
        "enemies": "Thorn-adapted creatures armored in bark, indistinguishable from the bushes until they move",
        "friends": "A path-cutter hired to maintain a trail through the thicket, grateful for an extra blade",
        "complications": "The thorns grow visibly fast; a path cut today will be closed by tomorrow",
        "things": "Thorn sap collected in a vial, useful as a potent if painful antiseptic",
        "places": "A hollow at the thicket's heart where something has cleared the thorns in a perfect circle",
    },
    {
        "name": "Obelisk Plain",
        "description": "Dozens of black stone obelisks rise from the flat earth at precise intervals, humming with residual energy.",
        "enemies": "Guardians that materialize near the obelisks when they are touched or damaged",
        "friends": "A geometer mapping the obelisk positions, convinced they form a mathematical message",
        "complications": "The obelisks interfere with navigation; compasses spin and the stars seem wrong from between them",
        "things": "A fragment broken from one obelisk, warm to the touch and inscribed with geometric patterns",
        "places": "The central obelisk, taller than the rest, with a door-shaped seam visible on one face",
    },
]
