"""Wilderness environment tags for scene generation.

Each tag provides elements (enemies, friends, complications, things, places)
that scene.py combines to create emergent exploration scenes. Tags evoke the
Latter Earth setting: a post-apocalyptic fantasy world built on the ruins of
prior civilizations, where ancient magic and mundane survival coexist.
"""

WILDERNESS_TAGS = [
    {
        "name": "Blighted Grove",
        "description": "Trees here grow twisted and dark, their bark weeping an oily sap that stains the earth.",
        "enemies": "A pack of feral beasts warped by the blight, eyes gleaming with unnatural hunger",
        "friends": "A wandering herbalist gathering samples of the corruption for study",
        "complications": "The blight is spreading visibly; staying too long risks contamination",
        "things": "A cracked crystal embedded in the largest tree, pulsing with faint light",
        "places": "A clearing where nothing grows, the soil fused to black glass",
    },
    {
        "name": "Ancient Road",
        "description": "A perfectly straight road of fitted stone stretches across the landscape, built by hands long forgotten.",
        "enemies": "Bandits using the road as a hunting ground for lone travelers",
        "friends": "A merchant caravan grateful for company on the dangerous stretch",
        "complications": "Sections of the road have collapsed into sinkholes revealing tunnels below",
        "things": "Carved milestones with distances to cities that no longer exist",
        "places": "A ruined waystation with a still-functioning cistern",
    },
    {
        "name": "Singing Stones",
        "description": "Tall standing stones emit a low harmonic hum when the wind passes through them.",
        "enemies": "A territorial creature that has made its lair among the stones",
        "friends": "A scholar documenting the tonal patterns, believing they encode a message",
        "complications": "The harmonics intensify at night, attracting dangerous predators",
        "things": "A tuning fork of unknown metal that resonates with the stones",
        "places": "The central ring where the harmonics converge into a single clear note",
    },
    {
        "name": "Flooded Lowland",
        "description": "Seasonal rains have turned this low valley into a shallow marsh of mud and standing water.",
        "enemies": "Amphibious predators lurking beneath the murky water",
        "friends": "A fishing family in a stilted shelter willing to share their catch",
        "complications": "The water is rising steadily and may soon cut off the only dry path",
        "things": "The top of a buried structure visible just above the waterline",
        "places": "An island of dry ground crowned by a massive dead tree",
    },
    {
        "name": "Ember Waste",
        "description": "The ground here is warm to the touch, and thin smoke rises from cracks in the earth.",
        "enemies": "Fire-adapted lizards the size of dogs that hunt in coordinated packs",
        "friends": "A prospector extracting heat-forged minerals from the vents",
        "complications": "Sudden gouts of flame erupt from the ground without warning",
        "things": "A vein of glass-like mineral formed by extreme underground heat",
        "places": "A natural hot spring surrounded by mineral deposits in vivid colors",
    },
    {
        "name": "Bone Field",
        "description": "The remains of enormous creatures litter this plain, their ribcages large enough to shelter under.",
        "enemies": "Scavengers that fiercely defend the bones as their territory",
        "friends": "A nomad band that camps in the shelter of a massive skull",
        "complications": "Something is killing creatures here regularly — the bones are fresh beneath the old",
        "things": "A tooth as long as a sword, carved with tiny script in an unknown language",
        "places": "A complete skeleton arched over the trail like a gateway",
    },
    {
        "name": "Mist Hollow",
        "description": "A perpetual fog fills this depression, limiting visibility to a few paces.",
        "enemies": "Predators that have adapted to hunt by sound in the dense fog",
        "friends": "A lost traveler calling out, desperate for a guide through the mist",
        "complications": "The mist distorts direction; compasses spin and landmarks vanish",
        "things": "A lantern that burns without fuel, found hanging from a dead branch",
        "places": "A stone bridge over a chasm invisible until you nearly step into it",
    },
    {
        "name": "Skyfall Crater",
        "description": "A vast circular depression marks where something fell from the heavens in ages past.",
        "enemies": "Opportunistic raiders camped on the crater rim, ambushing those who descend",
        "friends": "An astronomer from a distant city studying the impact site",
        "complications": "Metal objects behave strangely near the crater center — weapons pull toward the ground",
        "things": "Shards of a strange dark metal scattered across the crater floor",
        "places": "The crater center, where a pool of unnaturally still water reflects no sky",
    },
    {
        "name": "Thornwall",
        "description": "A barrier of thorny vegetation stretches as far as the eye can see, impenetrable and ancient.",
        "enemies": "Territorial vine-creatures that animate from the thornwall when disturbed",
        "friends": "A guide who knows a hidden passage through the barrier",
        "complications": "The thorns are mildly venomous; scratches cause fever and disorientation",
        "things": "A preserved corpse entangled in the thorns, its pack still intact",
        "places": "A natural arch in the thornwall where the vines have grown into a tunnel",
    },
    {
        "name": "Salt Flat",
        "description": "A blinding white expanse of crystallized salt stretches to the horizon under a merciless sun.",
        "enemies": "A salt devil pack hunting across the flat, camouflaged against the white ground",
        "friends": "Salt harvesters from a nearby community working the edges of the flat",
        "complications": "The crust is thin in places; breaking through reveals corrosive brine below",
        "things": "A perfectly preserved ancient artifact encased in salt crystal",
        "places": "A salt pillar formation that provides the only shade for miles",
    },
    {
        "name": "Petrified Forest",
        "description": "Stone trees stand in silent rows, turned to rock by some ancient catastrophe.",
        "enemies": "A stone-skinned predator that blends perfectly with the petrified trunks",
        "friends": "A stonemason harvesting petrified wood for a wealthy patron",
        "complications": "The petrification effect may still be active in places — flesh touching bare stone tingles",
        "things": "A petrified bird mid-flight, wings spread, impossibly balanced on a branch",
        "places": "A hollow in a massive petrified trunk, large enough to camp inside",
    },
    {
        "name": "Witch-Light Fen",
        "description": "Ghostly lights drift over the bog at night, and the locals refuse to enter after dark.",
        "enemies": "Bog-drowned undead that rise from the peat when the lights appear",
        "friends": "A hedge witch who harvests rare plants from the fen by day",
        "complications": "The safe paths shift with the seasons; yesterday's trail is today's drowning pool",
        "things": "A preserved offering to a forgotten god, wrapped in waxed cloth",
        "places": "A sunken temple half-submerged in black water, its altar still above the surface",
    },
    {
        "name": "Wind-Carved Canyon",
        "description": "Millennia of wind have sculpted this canyon into impossible shapes and howling passages.",
        "enemies": "Flying predators that nest on the canyon walls and dive on travelers below",
        "friends": "A hermit who has mapped the canyon's wind patterns and safest routes",
        "complications": "Wind funnels through certain passages with enough force to knock a person down",
        "things": "Ancient carvings revealed by erosion, depicting scenes of a vanished people",
        "places": "A natural amphitheater where whispers carry perfectly from wall to wall",
    },
    {
        "name": "Fungal Bloom",
        "description": "Enormous mushrooms tower overhead, their caps blocking the sun and releasing clouds of spores.",
        "enemies": "Insectoid creatures the size of dogs that farm and defend the fungal colony",
        "friends": "A forager who knows which fungi are edible and which are lethal",
        "complications": "Breathing the spores without protection causes hallucinations within hours",
        "things": "A luminescent fungus that glows bright enough to read by",
        "places": "A hollow beneath a massive mushroom cap, dry and warm from the organism's heat",
    },
    {
        "name": "Iron Rain Scar",
        "description": "The ground is pockmarked with craters and littered with rusted metal fragments from a skyfall of iron.",
        "enemies": "Rust-colored predators that have adapted to the ferrous terrain",
        "friends": "Scrap-metal traders picking through the debris for salvageable pieces",
        "complications": "Lightning strikes here with alarming frequency, drawn by the metal deposits",
        "things": "A chunk of meteoric iron, star-forged and suitable for a master smith",
        "places": "The largest crater, now a rust-stained pond circled by twisted metal spires",
    },
    {
        "name": "Whispering Grassland",
        "description": "Tall grass stretches endlessly, swaying in patterns that seem deliberate and directed.",
        "enemies": "Ambush predators hidden in the tall grass, invisible until they strike",
        "friends": "A nomadic herder whose animals know the safe paths through the grass",
        "complications": "The grass conceals sinkholes and old foundations; footing is treacherous",
        "things": "A wind chime made of bone, hanging from a lone tree",
        "places": "A stone circle where the grass refuses to grow, the bare earth black and hard",
    },
    {
        "name": "Crystal Seep",
        "description": "Mineral-laden water rises from underground, depositing brilliant crystal formations across the rocks.",
        "enemies": "Creatures drawn to the crystals that defend their territory with savage intensity",
        "friends": "A jeweler carefully extracting small crystals for sale in distant markets",
        "complications": "The crystals are beautiful but sharp as razors; moving carelessly draws blood",
        "things": "A crystal formation that has grown around a humanoid skeleton, encasing it perfectly",
        "places": "A grotto where crystal stalactites chime in the draft like a carillon",
    },
    {
        "name": "Thunder Ridge",
        "description": "A high ridgeline where storms gather with unnatural frequency and violence.",
        "enemies": "A beast that hunts during storms, using thunder to mask its approach",
        "friends": "A weather-reader who predicts storms and sells safe passage windows",
        "complications": "A storm is building now; crossing the ridge means racing the lightning",
        "things": "A lightning-fused sand sculpture, glass fingers reaching skyward",
        "places": "A cave system in the ridge face, dry but echoing with thunder",
    },
    {
        "name": "Sunken Garden",
        "description": "A terraced depression where plants grow in impossible abundance, fed by an underground spring.",
        "enemies": "A territorial guardian beast that has claimed the garden as its hunting ground",
        "friends": "A reclusive cultivator who tends the rarest plants and trades for supplies",
        "complications": "The abundance attracts constant animal activity; something large visits at night",
        "things": "A medicinal plant of extreme rarity, worth a fortune to the right buyer",
        "places": "The spring source, a clear pool surrounded by ancient carved channels",
    },
    {
        "name": "Ash Dunes",
        "description": "Dunes of volcanic ash stretch across the landscape, soft and shifting underfoot.",
        "enemies": "Burrowing predators that move through the ash like fish through water",
        "friends": "Ash-sailors in a wind-driven sled who offer passage across the waste",
        "complications": "A tremor loosens the ash; a minor avalanche threatens to bury the trail",
        "things": "A glass bead necklace from a civilization buried beneath the ash",
        "places": "The top of a buried tower protruding from the ash, its window a dark invitation",
    },
    {
        "name": "Warden Trees",
        "description": "Massive ancient trees grow in a deliberate circle, their canopy forming a natural dome.",
        "enemies": "Outlaws who have fortified the tree ring as a hidden base",
        "friends": "A druid-like keeper who maintains the trees and shares forest knowledge",
        "complications": "The trees are sacred to a local community; trespassing invites retribution",
        "things": "A heartwood tablet carved with a map of the surrounding region in exquisite detail",
        "places": "The hollow center of the largest tree, a natural chamber three stories tall",
    },
    {
        "name": "Glass Lake",
        "description": "A perfectly still lake whose surface reflects like a mirror, undisturbed even by wind.",
        "enemies": "Something large moves beneath the surface, visible only as a dark shadow",
        "friends": "A hermit fisher who warns travelers about the lake's dangers",
        "complications": "The lake's edge is treacherously smooth; the water is deceptively deep",
        "things": "A sealed jar on the lakebed, visible through the crystal-clear water",
        "places": "A small island at the lake's center, reachable by a submerged stone causeway",
    },
]
