"""Character tags table for NPC generation.

A d100 table of NPC character tags representing personality traits, quirks,
and distinguishing features. Used during social encounter generation to
give NPCs memorable and mechanically relevant characteristics.

Each entry covers a 2-point roll range on d100 (1-2, 3-4, ..., 99-100).
"""

CHARACTER_TAGS = [
    {"roll_range": (1, 2), "tag": "Suspicious", "description": "Distrusts strangers and questions motives behind every gesture of goodwill."},
    {"roll_range": (3, 4), "tag": "Generous", "description": "Freely shares wealth and resources, sometimes to their own detriment."},
    {"roll_range": (5, 6), "tag": "Compulsive liar", "description": "Fabricates stories and details reflexively, even when the truth would serve better."},
    {"roll_range": (7, 8), "tag": "Battle-scarred", "description": "Bears visible wounds from past conflicts that mark them as a survivor."},
    {"roll_range": (9, 10), "tag": "Devout", "description": "Deeply committed to a faith or spiritual practice that shapes every decision."},
    {"roll_range": (11, 12), "tag": "Paranoid", "description": "Sees threats and conspiracies everywhere, constantly checking over their shoulder."},
    {"roll_range": (13, 14), "tag": "Jovial", "description": "Relentlessly cheerful and quick to laugh, putting others at ease."},
    {"roll_range": (15, 16), "tag": "Greedy", "description": "Obsessed with accumulating wealth and always angling for a better deal."},
    {"roll_range": (17, 18), "tag": "Melancholic", "description": "Carries a deep sadness, often lost in memories of better times."},
    {"roll_range": (19, 20), "tag": "Ambitious", "description": "Driven to climb in status and power, viewing every interaction as a stepping stone."},
    {"roll_range": (21, 22), "tag": "Cowardly", "description": "Avoids confrontation at all costs and folds under the slightest pressure."},
    {"roll_range": (23, 24), "tag": "Honorable", "description": "Bound by a strict personal code and refuses to break a sworn oath."},
    {"roll_range": (25, 26), "tag": "Vengeful", "description": "Nurses grudges for years and meticulously plans retribution against those who wronged them."},
    {"roll_range": (27, 28), "tag": "Scholarly", "description": "Endlessly curious about lore and knowledge, prone to lecturing at length."},
    {"roll_range": (29, 30), "tag": "Hedonistic", "description": "Lives for pleasure and comfort, indulging every appetite without restraint."},
    {"roll_range": (31, 32), "tag": "Stoic", "description": "Rarely shows emotion and endures hardship without complaint."},
    {"roll_range": (33, 34), "tag": "Hot-tempered", "description": "Erupts into anger with little provocation and struggles to control outbursts."},
    {"roll_range": (35, 36), "tag": "Calculating", "description": "Approaches every situation with cold logic, weighing costs and benefits before acting."},
    {"roll_range": (37, 38), "tag": "Superstitious", "description": "Clings to rituals, omens, and folk beliefs, refusing to tempt fate."},
    {"roll_range": (39, 40), "tag": "Charismatic", "description": "Possesses a magnetic personality that draws people in and inspires loyalty."},
    {"roll_range": (41, 42), "tag": "Secretive", "description": "Guards personal information jealously and speaks in half-truths and evasions."},
    {"roll_range": (43, 44), "tag": "Loyal", "description": "Devoted to their allies with an unshakeable bond that endures any trial."},
    {"roll_range": (45, 46), "tag": "Cruel", "description": "Takes pleasure in the suffering of others and exercises power without mercy."},
    {"roll_range": (47, 48), "tag": "Humble", "description": "Downplays their own abilities and achievements, deflecting praise to others."},
    {"roll_range": (49, 50), "tag": "Vain", "description": "Obsessed with personal appearance and reputation, easily flattered."},
    {"roll_range": (51, 52), "tag": "Pragmatic", "description": "Focuses on practical outcomes over ideals, willing to compromise principles for results."},
    {"roll_range": (53, 54), "tag": "Nostalgic", "description": "Constantly references the past and believes the old ways were superior."},
    {"roll_range": (55, 56), "tag": "Reckless", "description": "Acts impulsively without considering consequences, thriving on risk."},
    {"roll_range": (57, 58), "tag": "Compassionate", "description": "Deeply empathetic and moved by the suffering of others, often to their disadvantage."},
    {"roll_range": (59, 60), "tag": "Deceitful", "description": "Habitually manipulates others through charm, misdirection, and half-truths."},
    {"roll_range": (61, 62), "tag": "Fatalistic", "description": "Believes destiny is fixed and accepts whatever comes with grim resignation."},
    {"roll_range": (63, 64), "tag": "Perfectionist", "description": "Demands flawless execution in all things and is harshly critical of mistakes."},
    {"roll_range": (65, 66), "tag": "Garrulous", "description": "Talks incessantly and shares information freely, rarely knowing when to stop."},
    {"roll_range": (67, 68), "tag": "Taciturn", "description": "Speaks only when necessary, using as few words as possible."},
    {"roll_range": (69, 70), "tag": "Obsessive", "description": "Fixated on a single goal or subject to the exclusion of all else."},
    {"roll_range": (71, 72), "tag": "Diplomatic", "description": "Skilled at finding common ground and smoothing over conflicts between parties."},
    {"roll_range": (73, 74), "tag": "Bigoted", "description": "Holds deep prejudices against a particular group and refuses to question them."},
    {"roll_range": (75, 76), "tag": "Protective", "description": "Fiercely guards those in their care, sometimes to a smothering degree."},
    {"roll_range": (77, 78), "tag": "Envious", "description": "Constantly compares themselves to others and resents those who have more."},
    {"roll_range": (79, 80), "tag": "Ascetic", "description": "Rejects material comforts and lives a life of deliberate self-denial."},
    {"roll_range": (81, 82), "tag": "Cunning", "description": "Possesses a sharp, scheming mind always working two steps ahead of others."},
    {"roll_range": (83, 84), "tag": "Naive", "description": "Trusts too easily and takes people at face value, often exploited by the unscrupulous."},
    {"roll_range": (85, 86), "tag": "Haunted", "description": "Tormented by past deeds or experiences that intrude on waking life."},
    {"roll_range": (87, 88), "tag": "Stubborn", "description": "Refuses to change course once decided, no matter the evidence against their position."},
    {"roll_range": (89, 90), "tag": "Servile", "description": "Excessively deferential to authority, eager to please those above their station."},
    {"roll_range": (91, 92), "tag": "Rebellious", "description": "Instinctively opposes authority and chafes under any form of imposed order."},
    {"roll_range": (93, 94), "tag": "Pious fraud", "description": "Outwardly displays great virtue while privately indulging in vice."},
    {"roll_range": (95, 96), "tag": "World-weary", "description": "Has seen too much and approaches life with tired cynicism and low expectations."},
    {"roll_range": (97, 98), "tag": "Fanatical", "description": "Devoted to a cause with a burning intensity that brooks no compromise or doubt."},
    {"roll_range": (99, 100), "tag": "Eccentric", "description": "Behaves in bizarre and unpredictable ways that defy social convention."},
]
